//@version=6
// -----------------------------------------------------------------------------
// Title:         Standalone SMT (with Time-Based Pivot Engine) - IMMEDIATE PIVOTS
// Author:        Nick
// Version:       7.6.0
// Description: - Added two additional Time Session Filters, allowing for up to three distinct time windows for SMT plotting.
//              - Fixed a bug where 'Pivot A' labels for SMT Timeframes 3 and 4 were not being properly deleted.
//              - SMT labels now include the correlated asset's ticker for better context.
//              - MODIFIED: Pivot plotting now happens immediately when detected, not waiting for new HTF bar.
// -----------------------------------------------------------------------------

import TradingView/ta/6 as ta

indicator('Standalone SMT - Immediate Pivots', 'SMT Imm', overlay = true, max_labels_count=500, max_lines_count=500)

// =============================================================================
// INPUTS
// =============================================================================
string GRP_TIME_FILTER = "Time Session Filter"
enableTimeFilter1 = input.bool(false, "Enable Session Filter 1", group = GRP_TIME_FILTER, tooltip="If checked, the indicator will only plot SMT signals within this specified trading session.")
timeSession1 = input.session("0800-1200", "Trading Session 1", group = GRP_TIME_FILTER, tooltip="Define the time window for plotting SMTs. Format is HHMM-HHMM. The session is interpreted based on the chart's timezone setting. Example for London session: 0800-1700")
enableTimeFilter2 = input.bool(false, "Enable Session Filter 2", group = GRP_TIME_FILTER, tooltip="If checked, the indicator will only plot SMT signals within this specified trading session.")
timeSession2 = input.session("1300-1700", "Trading Session 2", group = GRP_TIME_FILTER, tooltip="Define the time window for plotting SMTs. Format is HHMM-HHMM. The session is interpreted based on the chart's timezone setting. Example for New York session: 1300-2200")
enableTimeFilter3 = input.bool(false, "Enable Session Filter 3", group = GRP_TIME_FILTER, tooltip="If checked, the indicator will only plot SMT signals within this specified trading session.")
timeSession3 = input.session("0000-0700", "Trading Session 3", group = GRP_TIME_FILTER, tooltip="Define the time window for plotting SMTs. Format is HHMM-HHMM. The session is interpreted based on the chart's timezone setting. Example for Asian session: 0000-0900")

string GRP_MASTER_ASSET = "Comparison Asset"
masterComparisonAsset = input.symbol("CME_MINI_DL:NQ1!", "Asset", group = GRP_MASTER_ASSET, tooltip = "Select the second asset to compare against the main chart's asset for detecting SMT.")
showPivotALabel = input.bool(true, "Show Pivot 'A' Label", group = GRP_MASTER_ASSET, tooltip = "A master switch to show or hide the 'A' label on the first pivot of all potential SMT setups across all timeframes.")

// --- SMT Timeframe 1 ---
string GRP_SMT1 = "SMT Settings (Timeframe 1)"
enableSMT1 = input.bool(true, "Enable Timeframe 1", group = GRP_SMT1, tooltip = "Master switch to turn the entire SMT detection logic on or off for the first timeframe.")
showPivotCrosses_SMT1 = input.bool(true, 'Show Pivots', group = GRP_SMT1, tooltip = "Toggles the visibility of the '+' markers on all identified Higher Timeframe pivots.")
enableEarlySmtDetection_SMT1 = input.bool(true, "Enable LTF Detection", group = GRP_SMT1, tooltip = "Enables the logic to look for SMT divergences on a lower timeframe (LTF), providing early, unconfirmed signals before the higher timeframe (HTF) bar closes.")
enableAlerts_SMT1 = input.bool(true, "Enable Alerts", group = GRP_SMT1, tooltip = "Enables alerts for both unconfirmed (LTF) and confirmed (HTF) SMT signals.")

string GRP_TIMEFRAMES_STRENGTH1 = "Timeframe & Strength Settings (Timeframe 1)"
timeframeInput_SMT1 = input.timeframe('240', 'Timeframe', group = GRP_TIMEFRAMES_STRENGTH1, tooltip = "Sets the higher timeframe (HTF) on which the main pivots are identified and SMTs are confirmed.")
leftBars_SMT1 = input.int(1, 'Left Strength', group = GRP_TIMEFRAMES_STRENGTH1, minval = 1, tooltip = "Defines the strength of a pivot. This is the number of bars to the left of a pivot candle that must have lower highs (for a pivot high) or higher lows (for a pivot low).")
rightBars_SMT1 = input.int(1, 'Right Strength', group = GRP_TIMEFRAMES_STRENGTH1, minval = 1, tooltip = "Defines the strength of a pivot. This is the number of bars to the right of a pivot candle that must have lower highs (for a pivot high) or higher lows (for a pivot low).")
intradayTimeframe_SMT1 = input.timeframe('15', "LTF Detection", group = GRP_TIMEFRAMES_STRENGTH1, tooltip = "Sets the lower timeframe (LTF) used for Early SMT Detection. The unconfirmed signals will only appear when your chart's timeframe is equal to or lower than this setting.")

string GRP_CROSSES_SMT1 = "Pivot Cross Colors (Timeframe 1)"
phColor_SMT1 = input.color(color.red, "High Color", group = GRP_CROSSES_SMT1, tooltip = "Sets the color for bearish elements: high pivots, bearish SMT lines, and labels.")
plColor_SMT1 = input.color(color.green, "Low Color", group = GRP_CROSSES_SMT1, tooltip = "Sets the color for bullish elements: low pivots, bullish SMT lines, and labels.")

// --- SMT Timeframe 2 ---
string GRP_SMT2 = "SMT Settings (Timeframe 2)"
enableSMT2 = input.bool(false, "Enable Timeframe 2", group = GRP_SMT2, tooltip = "Master switch to turn the entire SMT detection logic on or off for the second timeframe.")
showPivotCrosses_SMT2 = input.bool(true, 'Show Pivots', group = GRP_SMT2, tooltip = "Toggles the visibility of the '+' markers on all identified Higher Timeframe pivots.")
enableEarlySmtDetection_SMT2 = input.bool(true, "Enable LTF Detection", group = GRP_SMT2, tooltip = "Enables the logic to look for SMT divergences on a lower timeframe (LTF), providing early, unconfirmed signals before the higher timeframe (HTF) bar closes.")
enableAlerts_SMT2 = input.bool(true, "Enable Alerts", group = GRP_SMT2, tooltip = "Enables alerts for both unconfirmed (LTF) and confirmed (HTF) SMT signals.")

string GRP_TIMEFRAMES_STRENGTH2 = "Timeframe & Strength Settings (Timeframe 2)"
timeframeInput_SMT2 = input.timeframe('60', 'Timeframe', group = GRP_TIMEFRAMES_STRENGTH2, tooltip = "Sets the higher timeframe (HTF) on which the main pivots are identified and SMTs are confirmed.")
leftBars_SMT2 = input.int(2, 'Left Strength', group = GRP_TIMEFRAMES_STRENGTH2, minval = 1, tooltip = "Defines the strength of a pivot. This is the number of bars to the left of a pivot candle that must have lower highs (for a pivot high) or higher lows (for a pivot low).")
rightBars_SMT2 = input.int(2, 'Right Strength', group = GRP_TIMEFRAMES_STRENGTH2, minval = 1, tooltip = "Defines the strength of a pivot. This is the number of bars to the right of a pivot candle that must have lower highs (for a pivot high) or higher lows (for a pivot low).")
intradayTimeframe_SMT2 = input.timeframe('5', "LTF Detection", group = GRP_TIMEFRAMES_STRENGTH2, tooltip = "Sets the lower timeframe (LTF) used for Early SMT Detection. The unconfirmed signals will only appear when your chart's timeframe is equal to or lower than this setting.")

string GRP_CROSSES_SMT2 = "Pivot Cross Colors (Timeframe 2)"
phColor_SMT2 = input.color(color.orange, "High Color", group = GRP_CROSSES_SMT2, tooltip = "Sets the color for bearish elements: high pivots, bearish SMT lines, and labels.")
plColor_SMT2 = input.color(color.blue, "Low Color", group = GRP_CROSSES_SMT2, tooltip = "Sets the color for bullish elements: low pivots, bullish SMT lines, and labels.")

// --- SMT Timeframe 3 ---
string GRP_SMT3 = "SMT Settings (Timeframe 3)"
enableSMT3 = input.bool(false, "Enable Timeframe 3", group = GRP_SMT3)
showPivotCrosses_SMT3 = input.bool(true, 'Show Pivots', group = GRP_SMT3)
enableEarlySmtDetection_SMT3 = input.bool(true, "Enable LTF Detection", group = GRP_SMT3)
enableAlerts_SMT3 = input.bool(true, "Enable Alerts", group = GRP_SMT3)

string GRP_TIMEFRAMES_STRENGTH3 = "Timeframe & Strength Settings (Timeframe 3)"
timeframeInput_SMT3 = input.timeframe('D', 'Timeframe', group = GRP_TIMEFRAMES_STRENGTH3)
leftBars_SMT3 = input.int(3, 'Left Strength', group = GRP_TIMEFRAMES_STRENGTH3, minval = 1)
rightBars_SMT3 = input.int(3, 'Right Strength', group = GRP_TIMEFRAMES_STRENGTH3, minval = 1)
intradayTimeframe_SMT3 = input.timeframe('60', "LTF Detection", group = GRP_TIMEFRAMES_STRENGTH3)

string GRP_CROSSES_SMT3 = "Pivot Cross Colors (Timeframe 3)"
phColor_SMT3 = input.color(color.new(color.fuchsia, 20), "High Color", group = GRP_CROSSES_SMT3)
plColor_SMT3 = input.color(color.new(color.purple, 20), "Low Color", group = GRP_CROSSES_SMT3)

// --- SMT Timeframe 4 ---
string GRP_SMT4 = "SMT Settings (Timeframe 4)"
enableSMT4 = input.bool(false, "Enable Timeframe 4", group = GRP_SMT4)
showPivotCrosses_SMT4 = input.bool(true, 'Show Pivots', group = GRP_SMT4)
enableEarlySmtDetection_SMT4 = input.bool(true, "Enable LTF Detection", group = GRP_SMT4)
enableAlerts_SMT4 = input.bool(true, "Enable Alerts", group = GRP_SMT4)

string GRP_TIMEFRAMES_STRENGTH4 = "Timeframe & Strength Settings (Timeframe 4)"
timeframeInput_SMT4 = input.timeframe('W', 'Timeframe', group = GRP_TIMEFRAMES_STRENGTH4)
leftBars_SMT4 = input.int(4, 'Left Strength', group = GRP_TIMEFRAMES_STRENGTH4, minval = 1)
rightBars_SMT4 = input.int(4, 'Right Strength', group = GRP_TIMEFRAMES_STRENGTH4, minval = 1)
intradayTimeframe_SMT4 = input.timeframe('240', "LTF Detection", group = GRP_TIMEFRAMES_STRENGTH4)

string GRP_CROSSES_SMT4 = "Pivot Cross Colors (Timeframe 4)"
phColor_SMT4 = input.color(color.new(color.teal, 20), "High Color", group = GRP_CROSSES_SMT4)
plColor_SMT4 = input.color(color.new(color.aqua, 20), "Low Color", group = GRP_CROSSES_SMT4)

// --- SMT Timeframe 5 ---
string GRP_SMT5 = "SMT Settings (Timeframe 5)"
enableSMT5 = input.bool(false, "Enable Timeframe 5", group = GRP_SMT5)
showPivotCrosses_SMT5 = input.bool(true, 'Show Pivots', group = GRP_SMT5)
enableEarlySmtDetection_SMT5 = input.bool(true, "Enable LTF Detection", group = GRP_SMT5)
enableAlerts_SMT5 = input.bool(true, "Enable Alerts", group = GRP_SMT5)

string GRP_TIMEFRAMES_STRENGTH5 = "Timeframe & Strength Settings (Timeframe 5)"
timeframeInput_SMT5 = input.timeframe('30', 'Timeframe', group = GRP_TIMEFRAMES_STRENGTH5)
leftBars_SMT5 = input.int(5, 'Left Strength', group = GRP_TIMEFRAMES_STRENGTH5, minval = 1)
rightBars_SMT5 = input.int(5, 'Right Strength', group = GRP_TIMEFRAMES_STRENGTH5, minval = 1)
intradayTimeframe_SMT5 = input.timeframe('5', "LTF Detection", group = GRP_TIMEFRAMES_STRENGTH5)

string GRP_CROSSES_SMT5 = "Pivot Cross Colors (Timeframe 5)"
phColor_SMT5 = input.color(color.new(color.gray, 20), "High Color", group = GRP_CROSSES_SMT5)
plColor_SMT5 = input.color(color.new(color.silver, 20), "Low Color", group = GRP_CROSSES_SMT5)

// =============================================================================
// FUNCTIONS
// =============================================================================
int MAX_DRAWING_OBJECTS = 500

isWithinAnySession() =>
    anyFilterEnabled = enableTimeFilter1 or enableTimeFilter2 or enableTimeFilter3
    if not anyFilterEnabled
        true // No filters are enabled, so always allow plotting.
    else
        // At least one filter is enabled. Check if the current time falls into any of the ENABLED sessions.
        inSession1 = enableTimeFilter1 and not na(time(timeframe.period, timeSession1))
        inSession2 = enableTimeFilter2 and not na(time(timeframe.period, timeSession2))
        inSession3 = enableTimeFilter3 and not na(time(timeframe.period, timeSession3))
        inSession1 or inSession2 or inSession3 // Return true if in ANY of the enabled sessions.

getTicker(symbolString) =>
    str.contains(symbolString, ":") ? str.substring(symbolString, str.pos(symbolString, ":") + 1, str.length(symbolString)) : symbolString

formatTimeframe(string tf) =>
    var result = tf
    float tf_minutes = str.tonumber(tf)
    if not na(tf_minutes)
        if tf_minutes >= 60 and tf_minutes % 60 == 0
            result := str.tostring(int(tf_minutes / 60)) + 'H'
        else
            result := str.tostring(int(tf_minutes)) + 'M'
    result

checkForPivot(array<float> history, int pivot_idx, int left_strength, int right_strength, bool is_high) =>
    is_pivot = true
    if array.size(history) < left_strength + right_strength + 1 or pivot_idx < left_strength or pivot_idx > array.size(history) - 1 - right_strength
        is_pivot := false
    else
        pivot_price = array.get(history, pivot_idx)
        for i = 0 to left_strength + right_strength
            if i != left_strength
                neighbor_price = array.get(history, pivot_idx - left_strength + i)
                if is_high and neighbor_price >= pivot_price
                    is_pivot := false
                    break
                if not is_high and neighbor_price <= pivot_price
                    is_pivot := false
                    break
    is_pivot

drawPivotCross(array<label> labelsArray, int bar_time, float price, color p_color) =>
    label newLabel = label.new(bar_time, price, xloc=xloc.bar_time, style=label.style_xcross, color=p_color, size=size.tiny)
    array.push(labelsArray, newLabel)
    if array.size(labelsArray) > MAX_DRAWING_OBJECTS
        label.delete(array.shift(labelsArray))

// =============================================================================
// SMT 1: LOGIC CHECKS
// =============================================================================
bool isHistoryCollectionActive_SMT1 = enableSMT1 and timeframeInput_SMT1 != ''
bool is_new_htf_bar_SMT1 = isHistoryCollectionActive_SMT1 and (nz(ta.change(time(timeframeInput_SMT1))) != 0)
bool isHtfChartTimeframeValid_SMT1 = timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(timeframeInput_SMT1)
bool isSmtLogicActive_SMT1 = isHtfChartTimeframeValid_SMT1 and isHistoryCollectionActive_SMT1 and enableSMT1 and masterComparisonAsset != ""

// =============================================================================
// SMT 1: HISTORY COLLECTION BLOCKS
// =============================================================================
var label[] smt1_PivotLabels = array.new_label()
var float smt1_session_high = high, var float smt1_session_low = low
var int smt1_session_high_time = time, var int smt1_session_low_time = time
var array<float> smt1_history_highs = array.new_float(), var array<float> smt1_history_lows = array.new_float()
var array<int> smt1_history_times_high = array.new_int(), var array<int> smt1_history_times_low = array.new_int()
var array<float> smt1_comp_history_highs = array.new_float(), var array<float> smt1_comp_history_lows = array.new_float()

if isHistoryCollectionActive_SMT1
    if is_new_htf_bar_SMT1
        smt1_session_high := high, smt1_session_low := low
        smt1_session_high_time := time, smt1_session_low_time := time
    else
        if high >= smt1_session_high
            smt1_session_high := high, smt1_session_high_time := time
        if low <= smt1_session_low
            smt1_session_low := low, smt1_session_low_time := time
    if is_new_htf_bar_SMT1
        array.push(smt1_history_highs, smt1_session_high[1]), array.push(smt1_history_times_high, smt1_session_high_time[1])
        array.push(smt1_history_lows, smt1_session_low[1]), array.push(smt1_history_times_low, smt1_session_low_time[1])
        float comp_high = request.security(masterComparisonAsset, timeframeInput_SMT1, high[1], lookahead=barmerge.lookahead_on)
        float comp_low = request.security(masterComparisonAsset, timeframeInput_SMT1, low[1], lookahead=barmerge.lookahead_on)
        array.push(smt1_comp_history_highs, comp_high), array.push(smt1_comp_history_lows, comp_low)

// IMMEDIATE PIVOT PLOTTING - MOVED OUTSIDE HTF BAR CONDITION
if showPivotCrosses_SMT1 and array.size(smt1_history_highs) > 0
    int pivot_check_index = array.size(smt1_history_highs) - 1 - rightBars_SMT1
    if pivot_check_index >= 0
        if checkForPivot(smt1_history_highs, pivot_check_index, leftBars_SMT1, rightBars_SMT1, true)
            drawPivotCross(smt1_PivotLabels, array.get(smt1_history_times_high, pivot_check_index), array.get(smt1_history_highs, pivot_check_index), phColor_SMT1)
        if checkForPivot(smt1_history_lows, pivot_check_index, leftBars_SMT1, rightBars_SMT1, false)
            drawPivotCross(smt1_PivotLabels, array.get(smt1_history_times_low, pivot_check_index), array.get(smt1_history_lows, pivot_check_index), plColor_SMT1)

// =============================================================================
// SMT 1: LOGIC
// =============================================================================
var label pivotA_HighLabel_SMT1 = na, var label visualPivotA_HighLabel_SMT1 = na, var label pivotA_LowLabel_SMT1 = na, var label visualPivotA_LowLabel_SMT1 = na, var line intraDayHighWatchline_SMT1 = na, var line intraDayLowWatchline_SMT1 = na, var label intraDayHighLabel_SMT1 = na, var label intraDayLowLabel_SMT1 = na, var float intraDayWatchlineHighPrice_SMT1 = na, var float intraDayWatchlineLowPrice_SMT1 = na, var bool ltfMainAssetInvalidatedHigh_SMT1 = false, var bool ltfCompAssetInvalidatedHigh_SMT1 = false, var bool ltfMainAssetInvalidatedLow_SMT1 = false, var bool ltfCompAssetInvalidatedLow_SMT1 = false
var array<line> smtConfirmedLines_SMT1 = array.new_line(), var array<label> smtConfirmedLabels_SMT1 = array.new_label()

cleanupSmtDrawings1() =>
    for l in smtConfirmedLines_SMT1
        line.delete(l)
    array.clear(smtConfirmedLines_SMT1)
    for l in smtConfirmedLabels_SMT1
        label.delete(l)
    array.clear(smtConfirmedLabels_SMT1)
    label.delete(pivotA_HighLabel_SMT1), label.delete(visualPivotA_HighLabel_SMT1)
    label.delete(pivotA_LowLabel_SMT1), label.delete(visualPivotA_LowLabel_SMT1)
    line.delete(intraDayHighWatchline_SMT1), label.delete(intraDayHighLabel_SMT1)
    line.delete(intraDayLowWatchline_SMT1), label.delete(intraDayLowLabel_SMT1)

if isSmtLogicActive_SMT1
    bool isWithinTimeSession = isWithinAnySession()
    string shortAssetName = getTicker(masterComparisonAsset)
    float atr_SMT1 = ta.atr(14)
    float y_offset_SMT1 = atr_SMT1 * 0.1
    if is_new_htf_bar_SMT1
        int pivot_idx = array.size(smt1_history_highs) - 1 - rightBars_SMT1
        if pivot_idx >= 0
            bool is_main_pivot_high = checkForPivot(smt1_history_highs, pivot_idx, leftBars_SMT1, rightBars_SMT1, true)
            bool is_comp_pivot_high = checkForPivot(smt1_comp_history_highs, pivot_idx, leftBars_SMT1, rightBars_SMT1, true)
            if is_main_pivot_high and is_comp_pivot_high
                float mainHtfPivotHigh = array.get(smt1_history_highs, pivot_idx)
                float compHtfPivotHigh = array.get(smt1_comp_history_highs, pivot_idx)
                int smt_main_pivot_time = array.get(smt1_history_times_high, pivot_idx)
                if not na(pivotA_HighLabel_SMT1)
                    if (mainHtfPivotHigh - label.get_y(pivotA_HighLabel_SMT1)) * (compHtfPivotHigh - str.tonumber(label.get_text(pivotA_HighLabel_SMT1))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt1_history_times_high, i) > label.get_x(pivotA_HighLabel_SMT1)
                                if array.get(smt1_history_highs, i) > label.get_y(pivotA_HighLabel_SMT1)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT1), str.tostring(leftBars_SMT1), str.tostring(rightBars_SMT1))
                            line newLine = line.new(label.get_x(pivotA_HighLabel_SMT1), label.get_y(pivotA_HighLabel_SMT1), smt_main_pivot_time, mainHtfPivotHigh, xloc = xloc.bar_time, color=color.new(phColor_SMT1, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT1, "SMT Bearish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT1, 75), textcolor=color.white, style=label.style_label_down, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT1, newLine), array.push(smtConfirmedLabels_SMT1, newLabel)
                            if enableAlerts_SMT1
                                alert("Confirmed Bearish SMT on SMT TF1", alert.freq_once_per_bar)
                line.delete(intraDayHighWatchline_SMT1), intraDayHighWatchline_SMT1 := na, label.delete(intraDayHighLabel_SMT1), intraDayHighLabel_SMT1 := na, intraDayWatchlineHighPrice_SMT1 := na
                label.delete(pivotA_HighLabel_SMT1), label.delete(visualPivotA_HighLabel_SMT1)
                pivotA_HighLabel_SMT1 := label.new(smt_main_pivot_time, mainHtfPivotHigh, str.tostring(compHtfPivotHigh), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_HighLabel_SMT1 := label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT1, "A", xloc=xloc.bar_time, style=label.style_label_down, color=color.new(phColor_SMT1, 25), textcolor=color.white, size=size.small, tooltip="Pivot A High")
                ltfMainAssetInvalidatedHigh_SMT1 := false, ltfCompAssetInvalidatedHigh_SMT1 := false
            bool is_main_pivot_low = checkForPivot(smt1_history_lows, pivot_idx, leftBars_SMT1, rightBars_SMT1, false)
            bool is_comp_pivot_low = checkForPivot(smt1_comp_history_lows, pivot_idx, leftBars_SMT1, rightBars_SMT1, false)
            if is_main_pivot_low and is_comp_pivot_low
                float mainHtfPivotLow = array.get(smt1_history_lows, pivot_idx)
                float compHtfPivotLow = array.get(smt1_comp_history_lows, pivot_idx)
                int smt_main_pivot_time = array.get(smt1_history_times_low, pivot_idx)
                if not na(pivotA_LowLabel_SMT1)
                    if (mainHtfPivotLow - label.get_y(pivotA_LowLabel_SMT1)) * (compHtfPivotLow - str.tonumber(label.get_text(pivotA_LowLabel_SMT1))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt1_history_times_low, i) > label.get_x(pivotA_LowLabel_SMT1)
                                if array.get(smt1_history_lows, i) < label.get_y(pivotA_LowLabel_SMT1)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT1), str.tostring(leftBars_SMT1), str.tostring(rightBars_SMT1))
                            line newLine = line.new(label.get_x(pivotA_LowLabel_SMT1), label.get_y(pivotA_LowLabel_SMT1), smt_main_pivot_time, mainHtfPivotLow, xloc = xloc.bar_time, color=color.new(plColor_SMT1, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT1, "SMT Bullish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT1, 75), textcolor=color.white, style=label.style_label_up, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT1, newLine), array.push(smtConfirmedLabels_SMT1, newLabel)
                            if enableAlerts_SMT1
                                alert("Confirmed Bullish SMT on SMT TF1", alert.freq_once_per_bar)
                line.delete(intraDayLowWatchline_SMT1), intraDayLowWatchline_SMT1 := na, label.delete(intraDayLowLabel_SMT1), intraDayLowLabel_SMT1 := na, intraDayWatchlineLowPrice_SMT1 := na
                label.delete(pivotA_LowLabel_SMT1), label.delete(visualPivotA_LowLabel_SMT1)
                pivotA_LowLabel_SMT1 := label.new(smt_main_pivot_time, mainHtfPivotLow, str.tostring(compHtfPivotLow), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_LowLabel_SMT1 := label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT1, "A", xloc=xloc.bar_time, style=label.style_label_up, color=color.new(plColor_SMT1, 25), textcolor=color.white, size=size.small, tooltip="Pivot A Low")
                ltfMainAssetInvalidatedLow_SMT1 := false, ltfCompAssetInvalidatedLow_SMT1 := false
    if enableEarlySmtDetection_SMT1 and intradayTimeframe_SMT1 != '' and timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(intradayTimeframe_SMT1)
        bool is_new_intraday_bar = ta.change(time(intradayTimeframe_SMT1)) != 0
        var float intraday_session_high_SMT1 = high, var float intraday_session_low_SMT1 = low, var int intraday_session_high_time_SMT1 = time, var int intraday_session_low_time_SMT1 = time
        var string usedLtfTimeframe_SMT1 = intradayTimeframe_SMT1
        float intra_comp_high_realtime_SMT1 = request.security(masterComparisonAsset, intradayTimeframe_SMT1, high, lookahead=barmerge.lookahead_off)
        usedLtfTimeframe_SMT1 := intradayTimeframe_SMT1
        if na(intra_comp_high_realtime_SMT1)
            intra_comp_high_realtime_SMT1 := request.security(masterComparisonAsset, '15', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT1 := '15'
        if na(intra_comp_high_realtime_SMT1)
            intra_comp_high_realtime_SMT1 := request.security(masterComparisonAsset, '60', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT1 := '60'
        float intra_comp_low_realtime_SMT1 = request.security(masterComparisonAsset, intradayTimeframe_SMT1, low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT1)
            intra_comp_low_realtime_SMT1 := request.security(masterComparisonAsset, '15', low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT1)
            intra_comp_low_realtime_SMT1 := request.security(masterComparisonAsset, '60', low, lookahead=barmerge.lookahead_off)
        var float intraday_comp_session_high_SMT1 = intra_comp_high_realtime_SMT1, var float intraday_comp_session_low_SMT1 = intra_comp_low_realtime_SMT1
        if is_new_intraday_bar
            intraday_session_high_SMT1 := high, intraday_session_low_SMT1 := low, intraday_session_high_time_SMT1 := time, intraday_session_low_time_SMT1 := time
            intraday_comp_session_high_SMT1 := intra_comp_high_realtime_SMT1, intraday_comp_session_low_SMT1 := intra_comp_low_realtime_SMT1
        else
            if high > intraday_session_high_SMT1
                intraday_session_high_SMT1 := high, intraday_session_high_time_SMT1 := time
            if low < intraday_session_low_SMT1
                intraday_session_low_SMT1 := low, intraday_session_low_time_SMT1 := time
            if intra_comp_high_realtime_SMT1 > intraday_comp_session_high_SMT1
                intraday_comp_session_high_SMT1 := intra_comp_high_realtime_SMT1
            if intra_comp_low_realtime_SMT1 < intraday_comp_session_low_SMT1
                intraday_comp_session_low_SMT1 := intra_comp_low_realtime_SMT1
        if is_new_intraday_bar
            float ltf_main_high = intraday_session_high_SMT1[1], float ltf_main_low = intraday_session_low_SMT1[1]
            float intra_comp_high = intraday_comp_session_high_SMT1[1], float intra_comp_low = intraday_comp_session_low_SMT1[1]
            if not na(pivotA_HighLabel_SMT1)
                if not ltfMainAssetInvalidatedHigh_SMT1 and ltf_main_high > label.get_y(pivotA_HighLabel_SMT1)
                    ltfMainAssetInvalidatedHigh_SMT1 := true
                if not ltfCompAssetInvalidatedHigh_SMT1 and intra_comp_high > str.tonumber(label.get_text(pivotA_HighLabel_SMT1))
                    ltfCompAssetInvalidatedHigh_SMT1 := true
                if ltfMainAssetInvalidatedHigh_SMT1 and ltfCompAssetInvalidatedHigh_SMT1
                    label.delete(pivotA_HighLabel_SMT1), pivotA_HighLabel_SMT1 := na, label.delete(visualPivotA_HighLabel_SMT1), visualPivotA_HighLabel_SMT1 := na
                    line.delete(intraDayHighWatchline_SMT1), intraDayHighWatchline_SMT1 := na, label.delete(intraDayHighLabel_SMT1), intraDayHighLabel_SMT1 := na
            if not na(pivotA_LowLabel_SMT1)
                if not ltfMainAssetInvalidatedLow_SMT1 and ltf_main_low < label.get_y(pivotA_LowLabel_SMT1)
                    ltfMainAssetInvalidatedLow_SMT1 := true
                if not ltfCompAssetInvalidatedLow_SMT1 and intra_comp_low < str.tonumber(label.get_text(pivotA_LowLabel_SMT1))
                    ltfCompAssetInvalidatedLow_SMT1 := true
                if ltfMainAssetInvalidatedLow_SMT1 and ltfCompAssetInvalidatedLow_SMT1
                    label.delete(pivotA_LowLabel_SMT1), pivotA_LowLabel_SMT1 := na, label.delete(visualPivotA_LowLabel_SMT1), visualPivotA_LowLabel_SMT1 := na
                    line.delete(intraDayLowWatchline_SMT1), intraDayLowWatchline_SMT1 := na, label.delete(intraDayLowLabel_SMT1), intraDayLowLabel_SMT1 := na
            int ltf_main_high_time = intraday_session_high_time_SMT1[1], int ltf_main_low_time = intraday_session_low_time_SMT1[1]
            if not na(pivotA_HighLabel_SMT1)
                bool alreadyInvalidated = ltfMainAssetInvalidatedHigh_SMT1 and ltfCompAssetInvalidatedHigh_SMT1
                if not alreadyInvalidated and (ltf_main_high - label.get_y(pivotA_HighLabel_SMT1)) * (intra_comp_high - str.tonumber(label.get_text(pivotA_HighLabel_SMT1))) < 0 and (na(intraDayWatchlineHighPrice_SMT1) or ltf_main_high > intraDayWatchlineHighPrice_SMT1) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT1), str.tostring(leftBars_SMT1), str.tostring(rightBars_SMT1), formatTimeframe(usedLtfTimeframe_SMT1))
                    line.delete(intraDayHighWatchline_SMT1), label.delete(intraDayHighLabel_SMT1)
                    intraDayHighWatchline_SMT1 := line.new(label.get_x(pivotA_HighLabel_SMT1), label.get_y(pivotA_HighLabel_SMT1), ltf_main_high_time, ltf_main_high, xloc = xloc.bar_time, style=line.style_dashed, color=phColor_SMT1, width=1)
                    intraDayHighLabel_SMT1 := label.new(ltf_main_high_time, ltf_main_high + y_offset_SMT1, "SMT Bearish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT1, 75), textcolor=color.white, style=label.style_label_down, textalign=text.align_left)
                    intraDayWatchlineHighPrice_SMT1 := ltf_main_high, ltfMainAssetInvalidatedHigh_SMT1 := false, ltfCompAssetInvalidatedHigh_SMT1 := false
                    if enableAlerts_SMT1
                        alert("Potential Bearish SMT on SMT TF 1", alert.freq_once_per_bar)
            if not na(pivotA_LowLabel_SMT1)
                bool alreadyInvalidated = ltfMainAssetInvalidatedLow_SMT1 and ltfCompAssetInvalidatedLow_SMT1
                if not alreadyInvalidated and (ltf_main_low - label.get_y(pivotA_LowLabel_SMT1)) * (intra_comp_low - str.tonumber(label.get_text(pivotA_LowLabel_SMT1))) < 0 and (na(intraDayWatchlineLowPrice_SMT1) or ltf_main_low < intraDayWatchlineLowPrice_SMT1) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT1), str.tostring(leftBars_SMT1), str.tostring(rightBars_SMT1), formatTimeframe(usedLtfTimeframe_SMT1))
                    line.delete(intraDayLowWatchline_SMT1), label.delete(intraDayLowLabel_SMT1)
                    intraDayLowWatchline_SMT1 := line.new(label.get_x(pivotA_LowLabel_SMT1), label.get_y(pivotA_LowLabel_SMT1), ltf_main_low_time, ltf_main_low, xloc = xloc.bar_time, style=line.style_dashed, color=plColor_SMT1, width=1)
                    intraDayLowLabel_SMT1 := label.new(ltf_main_low_time, ltf_main_low - y_offset_SMT1, "SMT Bullish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT1, 75), textcolor=color.white, style=label.style_label_up, textalign=text.align_left)
                    intraDayWatchlineLowPrice_SMT1 := ltf_main_low, ltfMainAssetInvalidatedLow_SMT1 := false, ltfCompAssetInvalidatedLow_SMT1 := false
                    if enableAlerts_SMT1
                        alert("Potential Bullish SMT on SMT TF 1", alert.freq_once_per_bar)
    if not na(visualPivotA_HighLabel_SMT1)
        label.set_color(visualPivotA_HighLabel_SMT1, showPivotALabel ? color.new(phColor_SMT1, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_HighLabel_SMT1, showPivotALabel ? color.white : color.new(color.white, 100))
    if not na(visualPivotA_LowLabel_SMT1)
        label.set_color(visualPivotA_LowLabel_SMT1, showPivotALabel ? color.new(plColor_SMT1, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_LowLabel_SMT1, showPivotALabel ? color.white : color.new(color.white, 100))
else
    cleanupSmtDrawings1()
    pivotA_HighLabel_SMT1 := na, visualPivotA_HighLabel_SMT1 := na, pivotA_LowLabel_SMT1 := na, visualPivotA_LowLabel_SMT1 := na
    intraDayHighWatchline_SMT1 := na, intraDayHighLabel_SMT1 := na, intraDayLowWatchline_SMT1 := na, intraDayLowLabel_SMT1 := na

// =============================================================================
// SMT 2: LOGIC CHECKS
// =============================================================================
bool isHistoryCollectionActive_SMT2 = enableSMT2 and timeframeInput_SMT2 != ''
bool is_new_htf_bar_SMT2 = isHistoryCollectionActive_SMT2 and (nz(ta.change(time(timeframeInput_SMT2))) != 0)
bool isHtfChartTimeframeValid_SMT2 = timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(timeframeInput_SMT2)
bool isSmtLogicActive_SMT2 = isHtfChartTimeframeValid_SMT2 and isHistoryCollectionActive_SMT2 and enableSMT2 and masterComparisonAsset != ""

// =============================================================================
// SMT 2: HISTORY COLLECTION BLOCKS
// =============================================================================
var label[] smt2_PivotLabels = array.new_label()
var float smt2_session_high = high, var float smt2_session_low = low
var int smt2_session_high_time = time, var int smt2_session_low_time = time
var array<float> smt2_history_highs = array.new_float(), var array<float> smt2_history_lows = array.new_float()
var array<int> smt2_history_times_high = array.new_int(), var array<int> smt2_history_times_low = array.new_int()
var array<float> smt2_comp_history_highs = array.new_float(), var array<float> smt2_comp_history_lows = array.new_float()

if isHistoryCollectionActive_SMT2
    if is_new_htf_bar_SMT2
        smt2_session_high := high, smt2_session_low := low
        smt2_session_high_time := time, smt2_session_low_time := time
    else
        if high >= smt2_session_high
            smt2_session_high := high, smt2_session_high_time := time
        if low <= smt2_session_low
            smt2_session_low := low, smt2_session_low_time := time
    if is_new_htf_bar_SMT2
        array.push(smt2_history_highs, smt2_session_high[1]), array.push(smt2_history_times_high, smt2_session_high_time[1])
        array.push(smt2_history_lows, smt2_session_low[1]), array.push(smt2_history_times_low, smt2_session_low_time[1])
        float comp_high = request.security(masterComparisonAsset, timeframeInput_SMT2, high[1], lookahead=barmerge.lookahead_on)
        float comp_low = request.security(masterComparisonAsset, timeframeInput_SMT2, low[1], lookahead=barmerge.lookahead_on)
        array.push(smt2_comp_history_highs, comp_high), array.push(smt2_comp_history_lows, comp_low)

// IMMEDIATE PIVOT PLOTTING - MOVED OUTSIDE HTF BAR CONDITION
if showPivotCrosses_SMT2 and array.size(smt2_history_highs) > 0
    int pivot_check_index = array.size(smt2_history_highs) - 1 - rightBars_SMT2
    if pivot_check_index >= 0
        if checkForPivot(smt2_history_highs, pivot_check_index, leftBars_SMT2, rightBars_SMT2, true)
            drawPivotCross(smt2_PivotLabels, array.get(smt2_history_times_high, pivot_check_index), array.get(smt2_history_highs, pivot_check_index), phColor_SMT2)
        if checkForPivot(smt2_history_lows, pivot_check_index, leftBars_SMT2, rightBars_SMT2, false)
            drawPivotCross(smt2_PivotLabels, array.get(smt2_history_times_low, pivot_check_index), array.get(smt2_history_lows, pivot_check_index), plColor_SMT2)

// =============================================================================
// SMT 2: LOGIC
// =============================================================================
var label pivotA_HighLabel_SMT2 = na, var label visualPivotA_HighLabel_SMT2 = na, var label pivotA_LowLabel_SMT2 = na, var label visualPivotA_LowLabel_SMT2 = na, var line intraDayHighWatchline_SMT2 = na, var line intraDayLowWatchline_SMT2 = na, var label intraDayHighLabel_SMT2 = na, var label intraDayLowLabel_SMT2 = na, var float intraDayWatchlineHighPrice_SMT2 = na, var float intraDayWatchlineLowPrice_SMT2 = na, var bool ltfMainAssetInvalidatedHigh_SMT2 = false, var bool ltfCompAssetInvalidatedHigh_SMT2 = false, var bool ltfMainAssetInvalidatedLow_SMT2 = false, var bool ltfCompAssetInvalidatedLow_SMT2 = false
var array<line> smtConfirmedLines_SMT2 = array.new_line(), var array<label> smtConfirmedLabels_SMT2 = array.new_label()

cleanupSmtDrawings2() =>
    for l in smtConfirmedLines_SMT2
        line.delete(l)
    array.clear(smtConfirmedLines_SMT2)
    for l in smtConfirmedLabels_SMT2
        label.delete(l)
    array.clear(smtConfirmedLabels_SMT2)
    label.delete(pivotA_HighLabel_SMT2), label.delete(visualPivotA_HighLabel_SMT2)
    label.delete(pivotA_LowLabel_SMT2), label.delete(visualPivotA_LowLabel_SMT2)
    line.delete(intraDayHighWatchline_SMT2), label.delete(intraDayHighLabel_SMT2)
    line.delete(intraDayLowWatchline_SMT2), label.delete(intraDayLowLabel_SMT2)

if isSmtLogicActive_SMT2
    bool isWithinTimeSession = isWithinAnySession()
    string shortAssetName = getTicker(masterComparisonAsset)
    float atr_SMT2 = ta.atr(14)
    float y_offset_SMT2 = atr_SMT2 * 0.1
    if is_new_htf_bar_SMT2
        int pivot_idx = array.size(smt2_history_highs) - 1 - rightBars_SMT2
        if pivot_idx >= 0
            bool is_main_pivot_high = checkForPivot(smt2_history_highs, pivot_idx, leftBars_SMT2, rightBars_SMT2, true)
            bool is_comp_pivot_high = checkForPivot(smt2_comp_history_highs, pivot_idx, leftBars_SMT2, rightBars_SMT2, true)
            if is_main_pivot_high and is_comp_pivot_high
                float mainHtfPivotHigh = array.get(smt2_history_highs, pivot_idx)
                float compHtfPivotHigh = array.get(smt2_comp_history_highs, pivot_idx)
                int smt_main_pivot_time = array.get(smt2_history_times_high, pivot_idx)
                if not na(pivotA_HighLabel_SMT2)
                    if (mainHtfPivotHigh - label.get_y(pivotA_HighLabel_SMT2)) * (compHtfPivotHigh - str.tonumber(label.get_text(pivotA_HighLabel_SMT2))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt2_history_times_high, i) > label.get_x(pivotA_HighLabel_SMT2)
                                if array.get(smt2_history_highs, i) > label.get_y(pivotA_HighLabel_SMT2)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT2), str.tostring(leftBars_SMT2), str.tostring(rightBars_SMT2))
                            line newLine = line.new(label.get_x(pivotA_HighLabel_SMT2), label.get_y(pivotA_HighLabel_SMT2), smt_main_pivot_time, mainHtfPivotHigh, xloc = xloc.bar_time, color=color.new(phColor_SMT2, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT2, "SMT Bearish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT2, 75), textcolor=color.white, style=label.style_label_down, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT2, newLine), array.push(smtConfirmedLabels_SMT2, newLabel)
                            if enableAlerts_SMT2
                                alert("Confirmed Bearish SMT on SMT TF2", alert.freq_once_per_bar)
                line.delete(intraDayHighWatchline_SMT2), intraDayHighWatchline_SMT2 := na, label.delete(intraDayHighLabel_SMT2), intraDayHighLabel_SMT2 := na, intraDayWatchlineHighPrice_SMT2 := na
                label.delete(pivotA_HighLabel_SMT2), label.delete(visualPivotA_HighLabel_SMT2)
                pivotA_HighLabel_SMT2 := label.new(smt_main_pivot_time, mainHtfPivotHigh, str.tostring(compHtfPivotHigh), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_HighLabel_SMT2 := label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT2, "A", xloc=xloc.bar_time, style=label.style_label_down, color=color.new(phColor_SMT2, 25), textcolor=color.white, size=size.small, tooltip="Pivot A High")
                ltfMainAssetInvalidatedHigh_SMT2 := false, ltfCompAssetInvalidatedHigh_SMT2 := false
            bool is_main_pivot_low = checkForPivot(smt2_history_lows, pivot_idx, leftBars_SMT2, rightBars_SMT2, false)
            bool is_comp_pivot_low = checkForPivot(smt2_comp_history_lows, pivot_idx, leftBars_SMT2, rightBars_SMT2, false)
            if is_main_pivot_low and is_comp_pivot_low
                float mainHtfPivotLow = array.get(smt2_history_lows, pivot_idx)
                float compHtfPivotLow = array.get(smt2_comp_history_lows, pivot_idx)
                int smt_main_pivot_time = array.get(smt2_history_times_low, pivot_idx)
                if not na(pivotA_LowLabel_SMT2)
                    if (mainHtfPivotLow - label.get_y(pivotA_LowLabel_SMT2)) * (compHtfPivotLow - str.tonumber(label.get_text(pivotA_LowLabel_SMT2))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt2_history_times_low, i) > label.get_x(pivotA_LowLabel_SMT2)
                                if array.get(smt2_history_lows, i) < label.get_y(pivotA_LowLabel_SMT2)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT2), str.tostring(leftBars_SMT2), str.tostring(rightBars_SMT2))
                            line newLine = line.new(label.get_x(pivotA_LowLabel_SMT2), label.get_y(pivotA_LowLabel_SMT2), smt_main_pivot_time, mainHtfPivotLow, xloc = xloc.bar_time, color=color.new(plColor_SMT2, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT2, "SMT Bullish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT2, 75), textcolor=color.white, style=label.style_label_up, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT2, newLine), array.push(smtConfirmedLabels_SMT2, newLabel)
                            if enableAlerts_SMT2
                                alert("Confirmed Bullish SMT on SMT TF2", alert.freq_once_per_bar)
                line.delete(intraDayLowWatchline_SMT2), intraDayLowWatchline_SMT2 := na, label.delete(intraDayLowLabel_SMT2), intraDayLowLabel_SMT2 := na, intraDayWatchlineLowPrice_SMT2 := na
                label.delete(pivotA_LowLabel_SMT2), label.delete(visualPivotA_LowLabel_SMT2)
                pivotA_LowLabel_SMT2 := label.new(smt_main_pivot_time, mainHtfPivotLow, str.tostring(compHtfPivotLow), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_LowLabel_SMT2 := label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT2, "A", xloc=xloc.bar_time, style=label.style_label_up, color=color.new(plColor_SMT2, 25), textcolor=color.white, size=size.small, tooltip="Pivot A Low")
                ltfMainAssetInvalidatedLow_SMT2 := false, ltfCompAssetInvalidatedLow_SMT2 := false
    if enableEarlySmtDetection_SMT2 and intradayTimeframe_SMT2 != '' and timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(intradayTimeframe_SMT2)
        bool is_new_intraday_bar = ta.change(time(intradayTimeframe_SMT2)) != 0
        var float intraday_session_high_SMT2 = high, var float intraday_session_low_SMT2 = low, var int intraday_session_high_time_SMT2 = time, var int intraday_session_low_time_SMT2 = time
        var string usedLtfTimeframe_SMT2 = intradayTimeframe_SMT2
        float intra_comp_high_realtime_SMT2 = request.security(masterComparisonAsset, intradayTimeframe_SMT2, high, lookahead=barmerge.lookahead_off)
        usedLtfTimeframe_SMT2 := intradayTimeframe_SMT2
        if na(intra_comp_high_realtime_SMT2)
            intra_comp_high_realtime_SMT2 := request.security(masterComparisonAsset, '15', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT2 := '15'
        if na(intra_comp_high_realtime_SMT2)
            intra_comp_high_realtime_SMT2 := request.security(masterComparisonAsset, '60', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT2 := '60'
        float intra_comp_low_realtime_SMT2 = request.security(masterComparisonAsset, intradayTimeframe_SMT2, low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT2)
            intra_comp_low_realtime_SMT2 := request.security(masterComparisonAsset, '15', low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT2)
            intra_comp_low_realtime_SMT2 := request.security(masterComparisonAsset, '60', low, lookahead=barmerge.lookahead_off)
        var float intraday_comp_session_high_SMT2 = intra_comp_high_realtime_SMT2, var float intraday_comp_session_low_SMT2 = intra_comp_low_realtime_SMT2
        if is_new_intraday_bar
            intraday_session_high_SMT2 := high, intraday_session_low_SMT2 := low, intraday_session_high_time_SMT2 := time, intraday_session_low_time_SMT2 := time
            intraday_comp_session_high_SMT2 := intra_comp_high_realtime_SMT2, intraday_comp_session_low_SMT2 := intra_comp_low_realtime_SMT2
        else
            if high > intraday_session_high_SMT2
                intraday_session_high_SMT2 := high, intraday_session_high_time_SMT2 := time
            if low < intraday_session_low_SMT2
                intraday_session_low_SMT2 := low, intraday_session_low_time_SMT2 := time
            if intra_comp_high_realtime_SMT2 > intraday_comp_session_high_SMT2
                intraday_comp_session_high_SMT2 := intra_comp_high_realtime_SMT2
            if intra_comp_low_realtime_SMT2 < intraday_comp_session_low_SMT2
                intraday_comp_session_low_SMT2 := intra_comp_low_realtime_SMT2
        if is_new_intraday_bar
            float ltf_main_high = intraday_session_high_SMT2[1], float ltf_main_low = intraday_session_low_SMT2[1]
            float intra_comp_high = intraday_comp_session_high_SMT2[1], float intra_comp_low = intraday_comp_session_low_SMT2[1]
            if not na(pivotA_HighLabel_SMT2)
                if not ltfMainAssetInvalidatedHigh_SMT2 and ltf_main_high > label.get_y(pivotA_HighLabel_SMT2)
                    ltfMainAssetInvalidatedHigh_SMT2 := true
                if not ltfCompAssetInvalidatedHigh_SMT2 and intra_comp_high > str.tonumber(label.get_text(pivotA_HighLabel_SMT2))
                    ltfCompAssetInvalidatedHigh_SMT2 := true
                if ltfMainAssetInvalidatedHigh_SMT2 and ltfCompAssetInvalidatedHigh_SMT2
                    label.delete(pivotA_HighLabel_SMT2), pivotA_HighLabel_SMT2 := na, label.delete(visualPivotA_HighLabel_SMT2), visualPivotA_HighLabel_SMT2 := na
                    line.delete(intraDayHighWatchline_SMT2), intraDayHighWatchline_SMT2 := na, label.delete(intraDayHighLabel_SMT2), intraDayHighLabel_SMT2 := na
            if not na(pivotA_LowLabel_SMT2)
                if not ltfMainAssetInvalidatedLow_SMT2 and ltf_main_low < label.get_y(pivotA_LowLabel_SMT2)
                    ltfMainAssetInvalidatedLow_SMT2 := true
                if not ltfCompAssetInvalidatedLow_SMT2 and intra_comp_low < str.tonumber(label.get_text(pivotA_LowLabel_SMT2))
                    ltfCompAssetInvalidatedLow_SMT2 := true
                if ltfMainAssetInvalidatedLow_SMT2 and ltfCompAssetInvalidatedLow_SMT2
                    label.delete(pivotA_LowLabel_SMT2), pivotA_LowLabel_SMT2 := na, label.delete(visualPivotA_LowLabel_SMT2), visualPivotA_LowLabel_SMT2 := na
                    line.delete(intraDayLowWatchline_SMT2), intraDayLowWatchline_SMT2 := na, label.delete(intraDayLowLabel_SMT2), intraDayLowLabel_SMT2 := na
            int ltf_main_high_time = intraday_session_high_time_SMT2[1], int ltf_main_low_time = intraday_session_low_time_SMT2[1]
            if not na(pivotA_HighLabel_SMT2)
                bool alreadyInvalidated = ltfMainAssetInvalidatedHigh_SMT2 and ltfCompAssetInvalidatedHigh_SMT2
                if not alreadyInvalidated and (ltf_main_high - label.get_y(pivotA_HighLabel_SMT2)) * (intra_comp_high - str.tonumber(label.get_text(pivotA_HighLabel_SMT2))) < 0 and (na(intraDayWatchlineHighPrice_SMT2) or ltf_main_high > intraDayWatchlineHighPrice_SMT2) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT2), str.tostring(leftBars_SMT2), str.tostring(rightBars_SMT2), formatTimeframe(usedLtfTimeframe_SMT2))
                    line.delete(intraDayHighWatchline_SMT2), label.delete(intraDayHighLabel_SMT2)
                    intraDayHighWatchline_SMT2 := line.new(label.get_x(pivotA_HighLabel_SMT2), label.get_y(pivotA_HighLabel_SMT2), ltf_main_high_time, ltf_main_high, xloc = xloc.bar_time, style=line.style_dashed, color=phColor_SMT2, width=1)
                    intraDayHighLabel_SMT2 := label.new(ltf_main_high_time, ltf_main_high + y_offset_SMT2, "SMT Bearish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT2, 75), textcolor=color.white, style=label.style_label_down, textalign=text.align_left)
                    intraDayWatchlineHighPrice_SMT2 := ltf_main_high, ltfMainAssetInvalidatedHigh_SMT2 := false, ltfCompAssetInvalidatedHigh_SMT2 := false
                    if enableAlerts_SMT2
                        alert("Potential Bearish SMT on SMT TF 2", alert.freq_once_per_bar)
            if not na(pivotA_LowLabel_SMT2)
                bool alreadyInvalidated = ltfMainAssetInvalidatedLow_SMT2 and ltfCompAssetInvalidatedLow_SMT2
                if not alreadyInvalidated and (ltf_main_low - label.get_y(pivotA_LowLabel_SMT2)) * (intra_comp_low - str.tonumber(label.get_text(pivotA_LowLabel_SMT2))) < 0 and (na(intraDayWatchlineLowPrice_SMT2) or ltf_main_low < intraDayWatchlineLowPrice_SMT2) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT2), str.tostring(leftBars_SMT2), str.tostring(rightBars_SMT2), formatTimeframe(usedLtfTimeframe_SMT2))
                    line.delete(intraDayLowWatchline_SMT2), label.delete(intraDayLowLabel_SMT2)
                    intraDayLowWatchline_SMT2 := line.new(label.get_x(pivotA_LowLabel_SMT2), label.get_y(pivotA_LowLabel_SMT2), ltf_main_low_time, ltf_main_low, xloc = xloc.bar_time, style=line.style_dashed, color=plColor_SMT2, width=1)
                    intraDayLowLabel_SMT2 := label.new(ltf_main_low_time, ltf_main_low - y_offset_SMT2, "SMT Bullish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT2, 75), textcolor=color.white, style=label.style_label_up, textalign=text.align_left)
                    intraDayWatchlineLowPrice_SMT2 := ltf_main_low, ltfMainAssetInvalidatedLow_SMT2 := false, ltfCompAssetInvalidatedLow_SMT2 := false
                    if enableAlerts_SMT2
                        alert("Potential Bullish SMT on SMT TF 2", alert.freq_once_per_bar)
    if not na(visualPivotA_HighLabel_SMT2)
        label.set_color(visualPivotA_HighLabel_SMT2, showPivotALabel ? color.new(phColor_SMT2, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_HighLabel_SMT2, showPivotALabel ? color.white : color.new(color.white, 100))
    if not na(visualPivotA_LowLabel_SMT2)
        label.set_color(visualPivotA_LowLabel_SMT2, showPivotALabel ? color.new(plColor_SMT2, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_LowLabel_SMT2, showPivotALabel ? color.white : color.new(color.white, 100))
else
    cleanupSmtDrawings2()
    pivotA_HighLabel_SMT2 := na, visualPivotA_HighLabel_SMT2 := na, pivotA_LowLabel_SMT2 := na, visualPivotA_LowLabel_SMT2 := na
    intraDayHighWatchline_SMT2 := na, intraDayHighLabel_SMT2 := na, intraDayLowWatchline_SMT2 := na, intraDayLowLabel_SMT2 := na

// =============================================================================
// SMT 3: LOGIC CHECKS
// =============================================================================
bool isHistoryCollectionActive_SMT3 = enableSMT3 and timeframeInput_SMT3 != ''
bool is_new_htf_bar_SMT3 = isHistoryCollectionActive_SMT3 and (nz(ta.change(time(timeframeInput_SMT3))) != 0)
bool isHtfChartTimeframeValid_SMT3 = timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(timeframeInput_SMT3)
bool isSmtLogicActive_SMT3 = isHtfChartTimeframeValid_SMT3 and isHistoryCollectionActive_SMT3 and enableSMT3 and masterComparisonAsset != ""

// =============================================================================
// SMT 3: HISTORY COLLECTION BLOCKS
// =============================================================================
var label[] smt3_PivotLabels = array.new_label()
var float smt3_session_high = high, var float smt3_session_low = low
var int smt3_session_high_time = time, var int smt3_session_low_time = time
var array<float> smt3_history_highs = array.new_float(), var array<float> smt3_history_lows = array.new_float()
var array<int> smt3_history_times_high = array.new_int(), var array<int> smt3_history_times_low = array.new_int()
var array<float> smt3_comp_history_highs = array.new_float(), var array<float> smt3_comp_history_lows = array.new_float()

if isHistoryCollectionActive_SMT3
    if is_new_htf_bar_SMT3
        smt3_session_high := high, smt3_session_low := low
        smt3_session_high_time := time, smt3_session_low_time := time
    else
        if high >= smt3_session_high
            smt3_session_high := high, smt3_session_high_time := time
        if low <= smt3_session_low
            smt3_session_low := low, smt3_session_low_time := time
    if is_new_htf_bar_SMT3
        array.push(smt3_history_highs, smt3_session_high[1]), array.push(smt3_history_times_high, smt3_session_high_time[1])
        array.push(smt3_history_lows, smt3_session_low[1]), array.push(smt3_history_times_low, smt3_session_low_time[1])
        float comp_high = request.security(masterComparisonAsset, timeframeInput_SMT3, high[1], lookahead=barmerge.lookahead_on)
        float comp_low = request.security(masterComparisonAsset, timeframeInput_SMT3, low[1], lookahead=barmerge.lookahead_on)
        array.push(smt3_comp_history_highs, comp_high), array.push(smt3_comp_history_lows, comp_low)

// IMMEDIATE PIVOT PLOTTING - MOVED OUTSIDE HTF BAR CONDITION
if showPivotCrosses_SMT3 and array.size(smt3_history_highs) > 0
    int pivot_check_index = array.size(smt3_history_highs) - 1 - rightBars_SMT3
    if pivot_check_index >= 0
        if checkForPivot(smt3_history_highs, pivot_check_index, leftBars_SMT3, rightBars_SMT3, true)
            drawPivotCross(smt3_PivotLabels, array.get(smt3_history_times_high, pivot_check_index), array.get(smt3_history_highs, pivot_check_index), phColor_SMT3)
        if checkForPivot(smt3_history_lows, pivot_check_index, leftBars_SMT3, rightBars_SMT3, false)
            drawPivotCross(smt3_PivotLabels, array.get(smt3_history_times_low, pivot_check_index), array.get(smt3_history_lows, pivot_check_index), plColor_SMT3)

// =============================================================================
// SMT 3: LOGIC
// =============================================================================
var label pivotA_HighLabel_SMT3 = na, var label visualPivotA_HighLabel_SMT3 = na, var label pivotA_LowLabel_SMT3 = na, var label visualPivotA_LowLabel_SMT3 = na, var line intraDayHighWatchline_SMT3 = na, var line intraDayLowWatchline_SMT3 = na, var label intraDayHighLabel_SMT3 = na, var label intraDayLowLabel_SMT3 = na, var float intraDayWatchlineHighPrice_SMT3 = na, var float intraDayWatchlineLowPrice_SMT3 = na, var bool ltfMainAssetInvalidatedHigh_SMT3 = false, var bool ltfCompAssetInvalidatedHigh_SMT3 = false, var bool ltfMainAssetInvalidatedLow_SMT3 = false, var bool ltfCompAssetInvalidatedLow_SMT3 = false
var array<line> smtConfirmedLines_SMT3 = array.new_line(), var array<label> smtConfirmedLabels_SMT3 = array.new_label()

cleanupSmtDrawings3() =>
    for l in smtConfirmedLines_SMT3
        line.delete(l)
    array.clear(smtConfirmedLines_SMT3)
    for l in smtConfirmedLabels_SMT3
        label.delete(l)
    array.clear(smtConfirmedLabels_SMT3)
    label.delete(pivotA_HighLabel_SMT3), label.delete(visualPivotA_HighLabel_SMT3)
    label.delete(pivotA_LowLabel_SMT3), label.delete(visualPivotA_LowLabel_SMT3)
    line.delete(intraDayHighWatchline_SMT3), label.delete(intraDayHighLabel_SMT3)
    line.delete(intraDayLowWatchline_SMT3), label.delete(intraDayLowLabel_SMT3)

if isSmtLogicActive_SMT3
    bool isWithinTimeSession = isWithinAnySession()
    string shortAssetName = getTicker(masterComparisonAsset)
    float atr_SMT3 = ta.atr(14)
    float y_offset_SMT3 = atr_SMT3 * 0.1
    if is_new_htf_bar_SMT3
        int pivot_idx = array.size(smt3_history_highs) - 1 - rightBars_SMT3
        if pivot_idx >= 0
            bool is_main_pivot_high = checkForPivot(smt3_history_highs, pivot_idx, leftBars_SMT3, rightBars_SMT3, true)
            bool is_comp_pivot_high = checkForPivot(smt3_comp_history_highs, pivot_idx, leftBars_SMT3, rightBars_SMT3, true)
            if is_main_pivot_high and is_comp_pivot_high
                float mainHtfPivotHigh = array.get(smt3_history_highs, pivot_idx)
                float compHtfPivotHigh = array.get(smt3_comp_history_highs, pivot_idx)
                int smt_main_pivot_time = array.get(smt3_history_times_high, pivot_idx)
                if not na(pivotA_HighLabel_SMT3)
                    if (mainHtfPivotHigh - label.get_y(pivotA_HighLabel_SMT3)) * (compHtfPivotHigh - str.tonumber(label.get_text(pivotA_HighLabel_SMT3))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt3_history_times_high, i) > label.get_x(pivotA_HighLabel_SMT3)
                                if array.get(smt3_history_highs, i) > label.get_y(pivotA_HighLabel_SMT3)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT3), str.tostring(leftBars_SMT3), str.tostring(rightBars_SMT3))
                            line newLine = line.new(label.get_x(pivotA_HighLabel_SMT3), label.get_y(pivotA_HighLabel_SMT3), smt_main_pivot_time, mainHtfPivotHigh, xloc = xloc.bar_time, color=color.new(phColor_SMT3, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT3, "SMT Bearish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT3, 75), textcolor=color.white, style=label.style_label_down, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT3, newLine), array.push(smtConfirmedLabels_SMT3, newLabel)
                            if enableAlerts_SMT3
                                alert("Confirmed Bearish SMT on SMT TF3", alert.freq_once_per_bar)
                line.delete(intraDayHighWatchline_SMT3), intraDayHighWatchline_SMT3 := na, label.delete(intraDayHighLabel_SMT3), intraDayHighLabel_SMT3 := na, intraDayWatchlineHighPrice_SMT3 := na
                label.delete(pivotA_HighLabel_SMT3), label.delete(visualPivotA_HighLabel_SMT3)
                pivotA_HighLabel_SMT3 := label.new(smt_main_pivot_time, mainHtfPivotHigh, str.tostring(compHtfPivotHigh), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_HighLabel_SMT3 := label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT3, "A", xloc=xloc.bar_time, style=label.style_label_down, color=color.new(phColor_SMT3, 25), textcolor=color.white, size=size.small, tooltip="Pivot A High")
                ltfMainAssetInvalidatedHigh_SMT3 := false, ltfCompAssetInvalidatedHigh_SMT3 := false
            bool is_main_pivot_low = checkForPivot(smt3_history_lows, pivot_idx, leftBars_SMT3, rightBars_SMT3, false)
            bool is_comp_pivot_low = checkForPivot(smt3_comp_history_lows, pivot_idx, leftBars_SMT3, rightBars_SMT3, false)
            if is_main_pivot_low and is_comp_pivot_low
                float mainHtfPivotLow = array.get(smt3_history_lows, pivot_idx)
                float compHtfPivotLow = array.get(smt3_comp_history_lows, pivot_idx)
                int smt_main_pivot_time = array.get(smt3_history_times_low, pivot_idx)
                if not na(pivotA_LowLabel_SMT3)
                    if (mainHtfPivotLow - label.get_y(pivotA_LowLabel_SMT3)) * (compHtfPivotLow - str.tonumber(label.get_text(pivotA_LowLabel_SMT3))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt3_history_times_low, i) > label.get_x(pivotA_LowLabel_SMT3)
                                if array.get(smt3_history_lows, i) < label.get_y(pivotA_LowLabel_SMT3)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT3), str.tostring(leftBars_SMT3), str.tostring(rightBars_SMT3))
                            line newLine = line.new(label.get_x(pivotA_LowLabel_SMT3), label.get_y(pivotA_LowLabel_SMT3), smt_main_pivot_time, mainHtfPivotLow, xloc = xloc.bar_time, color=color.new(plColor_SMT3, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT3, "SMT Bullish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT3, 75), textcolor=color.white, style=label.style_label_up, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT3, newLine), array.push(smtConfirmedLabels_SMT3, newLabel)
                            if enableAlerts_SMT3
                                alert("Confirmed Bullish SMT on SMT TF3", alert.freq_once_per_bar)
                line.delete(intraDayLowWatchline_SMT3), intraDayLowWatchline_SMT3 := na, label.delete(intraDayLowLabel_SMT3), intraDayLowLabel_SMT3 := na, intraDayWatchlineLowPrice_SMT3 := na
                label.delete(pivotA_LowLabel_SMT3), label.delete(visualPivotA_LowLabel_SMT3)
                pivotA_LowLabel_SMT3 := label.new(smt_main_pivot_time, mainHtfPivotLow, str.tostring(compHtfPivotLow), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_LowLabel_SMT3 := label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT3, "A", xloc=xloc.bar_time, style=label.style_label_up, color=color.new(plColor_SMT3, 25), textcolor=color.white, size=size.small, tooltip="Pivot A Low")
                ltfMainAssetInvalidatedLow_SMT3 := false, ltfCompAssetInvalidatedLow_SMT3 := false
    if enableEarlySmtDetection_SMT3 and intradayTimeframe_SMT3 != '' and timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(intradayTimeframe_SMT3)
        bool is_new_intraday_bar = ta.change(time(intradayTimeframe_SMT3)) != 0
        var float intraday_session_high_SMT3 = high, var float intraday_session_low_SMT3 = low, var int intraday_session_high_time_SMT3 = time, var int intraday_session_low_time_SMT3 = time
        var string usedLtfTimeframe_SMT3 = intradayTimeframe_SMT3
        float intra_comp_high_realtime_SMT3 = request.security(masterComparisonAsset, intradayTimeframe_SMT3, high, lookahead=barmerge.lookahead_off)
        usedLtfTimeframe_SMT3 := intradayTimeframe_SMT3
        if na(intra_comp_high_realtime_SMT3)
            intra_comp_high_realtime_SMT3 := request.security(masterComparisonAsset, '15', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT3 := '15'
        if na(intra_comp_high_realtime_SMT3)
            intra_comp_high_realtime_SMT3 := request.security(masterComparisonAsset, '60', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT3 := '60'
        float intra_comp_low_realtime_SMT3 = request.security(masterComparisonAsset, intradayTimeframe_SMT3, low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT3)
            intra_comp_low_realtime_SMT3 := request.security(masterComparisonAsset, '15', low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT3)
            intra_comp_low_realtime_SMT3 := request.security(masterComparisonAsset, '60', low, lookahead=barmerge.lookahead_off)
        var float intraday_comp_session_high_SMT3 = intra_comp_high_realtime_SMT3, var float intraday_comp_session_low_SMT3 = intra_comp_low_realtime_SMT3
        if is_new_intraday_bar
            intraday_session_high_SMT3 := high, intraday_session_low_SMT3 := low, intraday_session_high_time_SMT3 := time, intraday_session_low_time_SMT3 := time
            intraday_comp_session_high_SMT3 := intra_comp_high_realtime_SMT3, intraday_comp_session_low_SMT3 := intra_comp_low_realtime_SMT3
        else
            if high > intraday_session_high_SMT3
                intraday_session_high_SMT3 := high, intraday_session_high_time_SMT3 := time
            if low < intraday_session_low_SMT3
                intraday_session_low_SMT3 := low, intraday_session_low_time_SMT3 := time
            if intra_comp_high_realtime_SMT3 > intraday_comp_session_high_SMT3
                intraday_comp_session_high_SMT3 := intra_comp_high_realtime_SMT3
            if intra_comp_low_realtime_SMT3 < intraday_comp_session_low_SMT3
                intraday_comp_session_low_SMT3 := intra_comp_low_realtime_SMT3
        if is_new_intraday_bar
            float ltf_main_high = intraday_session_high_SMT3[1], float ltf_main_low = intraday_session_low_SMT3[1]
            float intra_comp_high = intraday_comp_session_high_SMT3[1], float intra_comp_low = intraday_comp_session_low_SMT3[1]
            if not na(pivotA_HighLabel_SMT3)
                if not ltfMainAssetInvalidatedHigh_SMT3 and ltf_main_high > label.get_y(pivotA_HighLabel_SMT3)
                    ltfMainAssetInvalidatedHigh_SMT3 := true
                if not ltfCompAssetInvalidatedHigh_SMT3 and intra_comp_high > str.tonumber(label.get_text(pivotA_HighLabel_SMT3))
                    ltfCompAssetInvalidatedHigh_SMT3 := true
                if ltfMainAssetInvalidatedHigh_SMT3 and ltfCompAssetInvalidatedHigh_SMT3
                    label.delete(pivotA_HighLabel_SMT3), pivotA_HighLabel_SMT3 := na, label.delete(visualPivotA_HighLabel_SMT3), visualPivotA_HighLabel_SMT3 := na
                    line.delete(intraDayHighWatchline_SMT3), intraDayHighWatchline_SMT3 := na, label.delete(intraDayHighLabel_SMT3), intraDayHighLabel_SMT3 := na
            if not na(pivotA_LowLabel_SMT3)
                if not ltfMainAssetInvalidatedLow_SMT3 and ltf_main_low < label.get_y(pivotA_LowLabel_SMT3)
                    ltfMainAssetInvalidatedLow_SMT3 := true
                if not ltfCompAssetInvalidatedLow_SMT3 and intra_comp_low < str.tonumber(label.get_text(pivotA_LowLabel_SMT3))
                    ltfCompAssetInvalidatedLow_SMT3 := true
                if ltfMainAssetInvalidatedLow_SMT3 and ltfCompAssetInvalidatedLow_SMT3
                    label.delete(pivotA_LowLabel_SMT3), pivotA_LowLabel_SMT3 := na, label.delete(visualPivotA_LowLabel_SMT3), visualPivotA_LowLabel_SMT3 := na
                    line.delete(intraDayLowWatchline_SMT3), intraDayLowWatchline_SMT3 := na, label.delete(intraDayLowLabel_SMT3), intraDayLowLabel_SMT3 := na
            int ltf_main_high_time = intraday_session_high_time_SMT3[1], int ltf_main_low_time = intraday_session_low_time_SMT3[1]
            if not na(pivotA_HighLabel_SMT3)
                bool alreadyInvalidated = ltfMainAssetInvalidatedHigh_SMT3 and ltfCompAssetInvalidatedHigh_SMT3
                if not alreadyInvalidated and (ltf_main_high - label.get_y(pivotA_HighLabel_SMT3)) * (intra_comp_high - str.tonumber(label.get_text(pivotA_HighLabel_SMT3))) < 0 and (na(intraDayWatchlineHighPrice_SMT3) or ltf_main_high > intraDayWatchlineHighPrice_SMT3) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT3), str.tostring(leftBars_SMT3), str.tostring(rightBars_SMT3), formatTimeframe(usedLtfTimeframe_SMT3))
                    line.delete(intraDayHighWatchline_SMT3), label.delete(intraDayHighLabel_SMT3)
                    intraDayHighWatchline_SMT3 := line.new(label.get_x(pivotA_HighLabel_SMT3), label.get_y(pivotA_HighLabel_SMT3), ltf_main_high_time, ltf_main_high, xloc = xloc.bar_time, style=line.style_dashed, color=phColor_SMT3, width=1)
                    intraDayHighLabel_SMT3 := label.new(ltf_main_high_time, ltf_main_high + y_offset_SMT3, "SMT Bearish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT3, 75), textcolor=color.white, style=label.style_label_down, textalign=text.align_left)
                    intraDayWatchlineHighPrice_SMT3 := ltf_main_high, ltfMainAssetInvalidatedHigh_SMT3 := false, ltfCompAssetInvalidatedHigh_SMT3 := false
                    if enableAlerts_SMT3
                        alert("Potential Bearish SMT on SMT TF 3", alert.freq_once_per_bar)
            if not na(pivotA_LowLabel_SMT3)
                bool alreadyInvalidated = ltfMainAssetInvalidatedLow_SMT3 and ltfCompAssetInvalidatedLow_SMT3
                if not alreadyInvalidated and (ltf_main_low - label.get_y(pivotA_LowLabel_SMT3)) * (intra_comp_low - str.tonumber(label.get_text(pivotA_LowLabel_SMT3))) < 0 and (na(intraDayWatchlineLowPrice_SMT3) or ltf_main_low < intraDayWatchlineLowPrice_SMT3) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT3), str.tostring(leftBars_SMT3), str.tostring(rightBars_SMT3), formatTimeframe(usedLtfTimeframe_SMT3))
                    line.delete(intraDayLowWatchline_SMT3), label.delete(intraDayLowLabel_SMT3)
                    intraDayLowWatchline_SMT3 := line.new(label.get_x(pivotA_LowLabel_SMT3), label.get_y(pivotA_LowLabel_SMT3), ltf_main_low_time, ltf_main_low, xloc = xloc.bar_time, style=line.style_dashed, color=plColor_SMT3, width=1)
                    intraDayLowLabel_SMT3 := label.new(ltf_main_low_time, ltf_main_low - y_offset_SMT3, "SMT Bullish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT3, 75), textcolor=color.white, style=label.style_label_up, textalign=text.align_left)
                    intraDayWatchlineLowPrice_SMT3 := ltf_main_low, ltfMainAssetInvalidatedLow_SMT3 := false, ltfCompAssetInvalidatedLow_SMT3 := false
                    if enableAlerts_SMT3
                        alert("Potential Bullish SMT on SMT TF 3", alert.freq_once_per_bar)
    if not na(visualPivotA_HighLabel_SMT3)
        label.set_color(visualPivotA_HighLabel_SMT3, showPivotALabel ? color.new(phColor_SMT3, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_HighLabel_SMT3, showPivotALabel ? color.white : color.new(color.white, 100))
    if not na(visualPivotA_LowLabel_SMT3)
        label.set_color(visualPivotA_LowLabel_SMT3, showPivotALabel ? color.new(plColor_SMT3, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_LowLabel_SMT3, showPivotALabel ? color.white : color.new(color.white, 100))
else
    cleanupSmtDrawings3()
    pivotA_HighLabel_SMT3 := na, visualPivotA_HighLabel_SMT3 := na, pivotA_LowLabel_SMT3 := na, visualPivotA_LowLabel_SMT3 := na
    intraDayHighWatchline_SMT3 := na, intraDayHighLabel_SMT3 := na, intraDayLowWatchline_SMT3 := na, intraDayLowLabel_SMT3 := na

// =============================================================================
// SMT 4: LOGIC CHECKS
// =============================================================================
bool isHistoryCollectionActive_SMT4 = enableSMT4 and timeframeInput_SMT4 != ''
bool is_new_htf_bar_SMT4 = isHistoryCollectionActive_SMT4 and (nz(ta.change(time(timeframeInput_SMT4))) != 0)
bool isHtfChartTimeframeValid_SMT4 = timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(timeframeInput_SMT4)
bool isSmtLogicActive_SMT4 = isHtfChartTimeframeValid_SMT4 and isHistoryCollectionActive_SMT4 and enableSMT4 and masterComparisonAsset != ""

// =============================================================================
// SMT 4: HISTORY COLLECTION BLOCKS
// =============================================================================
var label[] smt4_PivotLabels = array.new_label()
var float smt4_session_high = high, var float smt4_session_low = low
var int smt4_session_high_time = time, var int smt4_session_low_time = time
var array<float> smt4_history_highs = array.new_float(), var array<float> smt4_history_lows = array.new_float()
var array<int> smt4_history_times_high = array.new_int(), var array<int> smt4_history_times_low = array.new_int()
var array<float> smt4_comp_history_highs = array.new_float(), var array<float> smt4_comp_history_lows = array.new_float()

if isHistoryCollectionActive_SMT4
    if is_new_htf_bar_SMT4
        smt4_session_high := high, smt4_session_low := low
        smt4_session_high_time := time, smt4_session_low_time := time
    else
        if high >= smt4_session_high
            smt4_session_high := high, smt4_session_high_time := time
        if low <= smt4_session_low
            smt4_session_low := low, smt4_session_low_time := time
    if is_new_htf_bar_SMT4
        array.push(smt4_history_highs, smt4_session_high[1]), array.push(smt4_history_times_high, smt4_session_high_time[1])
        array.push(smt4_history_lows, smt4_session_low[1]), array.push(smt4_history_times_low, smt4_session_low_time[1])
        float comp_high = request.security(masterComparisonAsset, timeframeInput_SMT4, high[1], lookahead=barmerge.lookahead_on)
        float comp_low = request.security(masterComparisonAsset, timeframeInput_SMT4, low[1], lookahead=barmerge.lookahead_on)
        array.push(smt4_comp_history_highs, comp_high), array.push(smt4_comp_history_lows, comp_low)

// IMMEDIATE PIVOT PLOTTING - MOVED OUTSIDE HTF BAR CONDITION
if showPivotCrosses_SMT4 and array.size(smt4_history_highs) > 0
    int pivot_check_index = array.size(smt4_history_highs) - 1 - rightBars_SMT4
    if pivot_check_index >= 0
        if checkForPivot(smt4_history_highs, pivot_check_index, leftBars_SMT4, rightBars_SMT4, true)
            drawPivotCross(smt4_PivotLabels, array.get(smt4_history_times_high, pivot_check_index), array.get(smt4_history_highs, pivot_check_index), phColor_SMT4)
        if checkForPivot(smt4_history_lows, pivot_check_index, leftBars_SMT4, rightBars_SMT4, false)
            drawPivotCross(smt4_PivotLabels, array.get(smt4_history_times_low, pivot_check_index), array.get(smt4_history_lows, pivot_check_index), plColor_SMT4)

// =============================================================================
// SMT 4: LOGIC
// =============================================================================
var label pivotA_HighLabel_SMT4 = na, var label visualPivotA_HighLabel_SMT4 = na, var label pivotA_LowLabel_SMT4 = na, var label visualPivotA_LowLabel_SMT4 = na, var line intraDayHighWatchline_SMT4 = na, var line intraDayLowWatchline_SMT4 = na, var label intraDayHighLabel_SMT4 = na, var label intraDayLowLabel_SMT4 = na, var float intraDayWatchlineHighPrice_SMT4 = na, var float intraDayWatchlineLowPrice_SMT4 = na, var bool ltfMainAssetInvalidatedHigh_SMT4 = false, var bool ltfCompAssetInvalidatedHigh_SMT4 = false, var bool ltfMainAssetInvalidatedLow_SMT4 = false, var bool ltfCompAssetInvalidatedLow_SMT4 = false
var array<line> smtConfirmedLines_SMT4 = array.new_line(), var array<label> smtConfirmedLabels_SMT4 = array.new_label()

cleanupSmtDrawings4() =>
    for l in smtConfirmedLines_SMT4
        line.delete(l)
    array.clear(smtConfirmedLines_SMT4)
    for l in smtConfirmedLabels_SMT4
        label.delete(l)
    array.clear(smtConfirmedLabels_SMT4)
    label.delete(pivotA_HighLabel_SMT4), label.delete(visualPivotA_HighLabel_SMT4)
    label.delete(pivotA_LowLabel_SMT4), label.delete(visualPivotA_LowLabel_SMT4)
    line.delete(intraDayHighWatchline_SMT4), label.delete(intraDayHighLabel_SMT4)
    line.delete(intraDayLowWatchline_SMT4), label.delete(intraDayLowLabel_SMT4)

if isSmtLogicActive_SMT4
    bool isWithinTimeSession = isWithinAnySession()
    string shortAssetName = getTicker(masterComparisonAsset)
    float atr_SMT4 = ta.atr(14)
    float y_offset_SMT4 = atr_SMT4 * 0.1
    if is_new_htf_bar_SMT4
        int pivot_idx = array.size(smt4_history_highs) - 1 - rightBars_SMT4
        if pivot_idx >= 0
            bool is_main_pivot_high = checkForPivot(smt4_history_highs, pivot_idx, leftBars_SMT4, rightBars_SMT4, true)
            bool is_comp_pivot_high = checkForPivot(smt4_comp_history_highs, pivot_idx, leftBars_SMT4, rightBars_SMT4, true)
            if is_main_pivot_high and is_comp_pivot_high
                float mainHtfPivotHigh = array.get(smt4_history_highs, pivot_idx)
                float compHtfPivotHigh = array.get(smt4_comp_history_highs, pivot_idx)
                int smt_main_pivot_time = array.get(smt4_history_times_high, pivot_idx)
                if not na(pivotA_HighLabel_SMT4)
                    if (mainHtfPivotHigh - label.get_y(pivotA_HighLabel_SMT4)) * (compHtfPivotHigh - str.tonumber(label.get_text(pivotA_HighLabel_SMT4))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt4_history_times_high, i) > label.get_x(pivotA_HighLabel_SMT4)
                                if array.get(smt4_history_highs, i) > label.get_y(pivotA_HighLabel_SMT4)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT4), str.tostring(leftBars_SMT4), str.tostring(rightBars_SMT4))
                            line newLine = line.new(label.get_x(pivotA_HighLabel_SMT4), label.get_y(pivotA_HighLabel_SMT4), smt_main_pivot_time, mainHtfPivotHigh, xloc = xloc.bar_time, color=color.new(phColor_SMT4, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT4, "SMT Bearish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT4, 75), textcolor=color.white, style=label.style_label_down, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT4, newLine), array.push(smtConfirmedLabels_SMT4, newLabel)
                            if enableAlerts_SMT4
                                alert("Confirmed Bearish SMT on SMT TF4", alert.freq_once_per_bar)
                line.delete(intraDayHighWatchline_SMT4), intraDayHighWatchline_SMT4 := na, label.delete(intraDayHighLabel_SMT4), intraDayHighLabel_SMT4 := na, intraDayWatchlineHighPrice_SMT4 := na
                label.delete(pivotA_HighLabel_SMT4), label.delete(visualPivotA_HighLabel_SMT4)
                pivotA_HighLabel_SMT4 := label.new(smt_main_pivot_time, mainHtfPivotHigh, str.tostring(compHtfPivotHigh), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_HighLabel_SMT4 := label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT4, "A", xloc=xloc.bar_time, style=label.style_label_down, color=color.new(phColor_SMT4, 25), textcolor=color.white, size=size.small, tooltip="Pivot A High")
                ltfMainAssetInvalidatedHigh_SMT4 := false, ltfCompAssetInvalidatedHigh_SMT4 := false
            bool is_main_pivot_low = checkForPivot(smt4_history_lows, pivot_idx, leftBars_SMT4, rightBars_SMT4, false)
            bool is_comp_pivot_low = checkForPivot(smt4_comp_history_lows, pivot_idx, leftBars_SMT4, rightBars_SMT4, false)
            if is_main_pivot_low and is_comp_pivot_low
                float mainHtfPivotLow = array.get(smt4_history_lows, pivot_idx)
                float compHtfPivotLow = array.get(smt4_comp_history_lows, pivot_idx)
                int smt_main_pivot_time = array.get(smt4_history_times_low, pivot_idx)
                if not na(pivotA_LowLabel_SMT4)
                    if (mainHtfPivotLow - label.get_y(pivotA_LowLabel_SMT4)) * (compHtfPivotLow - str.tonumber(label.get_text(pivotA_LowLabel_SMT4))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt4_history_times_low, i) > label.get_x(pivotA_LowLabel_SMT4)
                                if array.get(smt4_history_lows, i) < label.get_y(pivotA_LowLabel_SMT4)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT4), str.tostring(leftBars_SMT4), str.tostring(rightBars_SMT4))
                            line newLine = line.new(label.get_x(pivotA_LowLabel_SMT4), label.get_y(pivotA_LowLabel_SMT4), smt_main_pivot_time, mainHtfPivotLow, xloc = xloc.bar_time, color=color.new(plColor_SMT4, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT4, "SMT Bullish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT4, 75), textcolor=color.white, style=label.style_label_up, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT4, newLine), array.push(smtConfirmedLabels_SMT4, newLabel)
                            if enableAlerts_SMT4
                                alert("Confirmed Bullish SMT on SMT TF4", alert.freq_once_per_bar)
                line.delete(intraDayLowWatchline_SMT4), intraDayLowWatchline_SMT4 := na, label.delete(intraDayLowLabel_SMT4), intraDayLowLabel_SMT4 := na, intraDayWatchlineLowPrice_SMT4 := na
                label.delete(pivotA_LowLabel_SMT4), label.delete(visualPivotA_LowLabel_SMT4)
                pivotA_LowLabel_SMT4 := label.new(smt_main_pivot_time, mainHtfPivotLow, str.tostring(compHtfPivotLow), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_LowLabel_SMT4 := label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT4, "A", xloc=xloc.bar_time, style=label.style_label_up, color=color.new(plColor_SMT4, 25), textcolor=color.white, size=size.small, tooltip="Pivot A Low")
                ltfMainAssetInvalidatedLow_SMT4 := false, ltfCompAssetInvalidatedLow_SMT4 := false
    if enableEarlySmtDetection_SMT4 and intradayTimeframe_SMT4 != '' and timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(intradayTimeframe_SMT4)
        bool is_new_intraday_bar = ta.change(time(intradayTimeframe_SMT4)) != 0
        var float intraday_session_high_SMT4 = high, var float intraday_session_low_SMT4 = low, var int intraday_session_high_time_SMT4 = time, var int intraday_session_low_time_SMT4 = time
        var string usedLtfTimeframe_SMT4 = intradayTimeframe_SMT4
        float intra_comp_high_realtime_SMT4 = request.security(masterComparisonAsset, intradayTimeframe_SMT4, high, lookahead=barmerge.lookahead_off)
        usedLtfTimeframe_SMT4 := intradayTimeframe_SMT4
        if na(intra_comp_high_realtime_SMT4)
            intra_comp_high_realtime_SMT4 := request.security(masterComparisonAsset, '15', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT4 := '15'
        if na(intra_comp_high_realtime_SMT4)
            intra_comp_high_realtime_SMT4 := request.security(masterComparisonAsset, '60', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT4 := '60'
        float intra_comp_low_realtime_SMT4 = request.security(masterComparisonAsset, intradayTimeframe_SMT4, low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT4)
            intra_comp_low_realtime_SMT4 := request.security(masterComparisonAsset, '15', low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT4)
            intra_comp_low_realtime_SMT4 := request.security(masterComparisonAsset, '60', low, lookahead=barmerge.lookahead_off)
        var float intraday_comp_session_high_SMT4 = intra_comp_high_realtime_SMT4, var float intraday_comp_session_low_SMT4 = intra_comp_low_realtime_SMT4
        if is_new_intraday_bar
            intraday_session_high_SMT4 := high, intraday_session_low_SMT4 := low, intraday_session_high_time_SMT4 := time, intraday_session_low_time_SMT4 := time
            intraday_comp_session_high_SMT4 := intra_comp_high_realtime_SMT4, intraday_comp_session_low_SMT4 := intra_comp_low_realtime_SMT4
        else
            if high > intraday_session_high_SMT4
                intraday_session_high_SMT4 := high, intraday_session_high_time_SMT4 := time
            if low < intraday_session_low_SMT4
                intraday_session_low_SMT4 := low, intraday_session_low_time_SMT4 := time
            if intra_comp_high_realtime_SMT4 > intraday_comp_session_high_SMT4
                intraday_comp_session_high_SMT4 := intra_comp_high_realtime_SMT4
            if intra_comp_low_realtime_SMT4 < intraday_comp_session_low_SMT4
                intraday_comp_session_low_SMT4 := intra_comp_low_realtime_SMT4
        if is_new_intraday_bar
            float ltf_main_high = intraday_session_high_SMT4[1], float ltf_main_low = intraday_session_low_SMT4[1]
            float intra_comp_high = intraday_comp_session_high_SMT4[1], float intra_comp_low = intraday_comp_session_low_SMT4[1]
            if not na(pivotA_HighLabel_SMT4)
                if not ltfMainAssetInvalidatedHigh_SMT4 and ltf_main_high > label.get_y(pivotA_HighLabel_SMT4)
                    ltfMainAssetInvalidatedHigh_SMT4 := true
                if not ltfCompAssetInvalidatedHigh_SMT4 and intra_comp_high > str.tonumber(label.get_text(pivotA_HighLabel_SMT4))
                    ltfCompAssetInvalidatedHigh_SMT4 := true
                if ltfMainAssetInvalidatedHigh_SMT4 and ltfCompAssetInvalidatedHigh_SMT4
                    label.delete(pivotA_HighLabel_SMT4), pivotA_HighLabel_SMT4 := na, label.delete(visualPivotA_HighLabel_SMT4), visualPivotA_HighLabel_SMT4 := na
                    line.delete(intraDayHighWatchline_SMT4), intraDayHighWatchline_SMT4 := na, label.delete(intraDayHighLabel_SMT4), intraDayHighLabel_SMT4 := na
            if not na(pivotA_LowLabel_SMT4)
                if not ltfMainAssetInvalidatedLow_SMT4 and ltf_main_low < label.get_y(pivotA_LowLabel_SMT4)
                    ltfMainAssetInvalidatedLow_SMT4 := true
                if not ltfCompAssetInvalidatedLow_SMT4 and intra_comp_low < str.tonumber(label.get_text(pivotA_LowLabel_SMT4))
                    ltfCompAssetInvalidatedLow_SMT4 := true
                if ltfMainAssetInvalidatedLow_SMT4 and ltfCompAssetInvalidatedLow_SMT4
                    label.delete(pivotA_LowLabel_SMT4), pivotA_LowLabel_SMT4 := na, label.delete(visualPivotA_LowLabel_SMT4), visualPivotA_LowLabel_SMT4 := na
                    line.delete(intraDayLowWatchline_SMT4), intraDayLowWatchline_SMT4 := na, label.delete(intraDayLowLabel_SMT4), intraDayLowLabel_SMT4 := na
            int ltf_main_high_time = intraday_session_high_time_SMT4[1], int ltf_main_low_time = intraday_session_low_time_SMT4[1]
            if not na(pivotA_HighLabel_SMT4)
                bool alreadyInvalidated = ltfMainAssetInvalidatedHigh_SMT4 and ltfCompAssetInvalidatedHigh_SMT4
                if not alreadyInvalidated and (ltf_main_high - label.get_y(pivotA_HighLabel_SMT4)) * (intra_comp_high - str.tonumber(label.get_text(pivotA_HighLabel_SMT4))) < 0 and (na(intraDayWatchlineHighPrice_SMT4) or ltf_main_high > intraDayWatchlineHighPrice_SMT4) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT4), str.tostring(leftBars_SMT4), str.tostring(rightBars_SMT4), formatTimeframe(usedLtfTimeframe_SMT4))
                    line.delete(intraDayHighWatchline_SMT4), label.delete(intraDayHighLabel_SMT4)
                    intraDayHighWatchline_SMT4 := line.new(label.get_x(pivotA_HighLabel_SMT4), label.get_y(pivotA_HighLabel_SMT4), ltf_main_high_time, ltf_main_high, xloc = xloc.bar_time, style=line.style_dashed, color=phColor_SMT4, width=1)
                    intraDayHighLabel_SMT4 := label.new(ltf_main_high_time, ltf_main_high + y_offset_SMT4, "SMT Bearish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT4, 75), textcolor=color.white, style=label.style_label_down, textalign=text.align_left)
                    intraDayWatchlineHighPrice_SMT4 := ltf_main_high, ltfMainAssetInvalidatedHigh_SMT4 := false, ltfCompAssetInvalidatedHigh_SMT4 := false
                    if enableAlerts_SMT4
                        alert("Potential Bearish SMT on SMT TF 4", alert.freq_once_per_bar)
            if not na(pivotA_LowLabel_SMT4)
                bool alreadyInvalidated = ltfMainAssetInvalidatedLow_SMT4 and ltfCompAssetInvalidatedLow_SMT4
                if not alreadyInvalidated and (ltf_main_low - label.get_y(pivotA_LowLabel_SMT4)) * (intra_comp_low - str.tonumber(label.get_text(pivotA_LowLabel_SMT4))) < 0 and (na(intraDayWatchlineLowPrice_SMT4) or ltf_main_low < intraDayWatchlineLowPrice_SMT4) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT4), str.tostring(leftBars_SMT4), str.tostring(rightBars_SMT4), formatTimeframe(usedLtfTimeframe_SMT4))
                    line.delete(intraDayLowWatchline_SMT4), label.delete(intraDayLowLabel_SMT4)
                    intraDayLowWatchline_SMT4 := line.new(label.get_x(pivotA_LowLabel_SMT4), label.get_y(pivotA_LowLabel_SMT4), ltf_main_low_time, ltf_main_low, xloc = xloc.bar_time, style=line.style_dashed, color=plColor_SMT4, width=1)
                    intraDayLowLabel_SMT4 := label.new(ltf_main_low_time, ltf_main_low - y_offset_SMT4, "SMT Bullish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT4, 75), textcolor=color.white, style=label.style_label_up, textalign=text.align_left)
                    intraDayWatchlineLowPrice_SMT4 := ltf_main_low, ltfMainAssetInvalidatedLow_SMT4 := false, ltfCompAssetInvalidatedLow_SMT4 := false
                    if enableAlerts_SMT4
                        alert("Potential Bullish SMT on SMT TF 4", alert.freq_once_per_bar)
    if not na(visualPivotA_HighLabel_SMT4)
        label.set_color(visualPivotA_HighLabel_SMT4, showPivotALabel ? color.new(phColor_SMT4, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_HighLabel_SMT4, showPivotALabel ? color.white : color.new(color.white, 100))
    if not na(visualPivotA_LowLabel_SMT4)
        label.set_color(visualPivotA_LowLabel_SMT4, showPivotALabel ? color.new(plColor_SMT4, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_LowLabel_SMT4, showPivotALabel ? color.white : color.new(color.white, 100))
else
    cleanupSmtDrawings4()
    pivotA_HighLabel_SMT4 := na, visualPivotA_HighLabel_SMT4 := na, pivotA_LowLabel_SMT4 := na, visualPivotA_LowLabel_SMT4 := na
    intraDayHighWatchline_SMT4 := na, intraDayHighLabel_SMT4 := na, intraDayLowWatchline_SMT4 := na, intraDayLowLabel_SMT4 := na

// =============================================================================
// SMT 5: LOGIC CHECKS
// =============================================================================
bool isHistoryCollectionActive_SMT5 = enableSMT5 and timeframeInput_SMT5 != ''
bool is_new_htf_bar_SMT5 = isHistoryCollectionActive_SMT5 and (nz(ta.change(time(timeframeInput_SMT5))) != 0)
bool isHtfChartTimeframeValid_SMT5 = timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(timeframeInput_SMT5)
bool isSmtLogicActive_SMT5 = isHtfChartTimeframeValid_SMT5 and isHistoryCollectionActive_SMT5 and enableSMT5 and masterComparisonAsset != ""

// =============================================================================
// SMT 5: HISTORY COLLECTION BLOCKS
// =============================================================================
var label[] smt5_PivotLabels = array.new_label()
var float smt5_session_high = high, var float smt5_session_low = low
var int smt5_session_high_time = time, var int smt5_session_low_time = time
var array<float> smt5_history_highs = array.new_float(), var array<float> smt5_history_lows = array.new_float()
var array<int> smt5_history_times_high = array.new_int(), var array<int> smt5_history_times_low = array.new_int()
var array<float> smt5_comp_history_highs = array.new_float(), var array<float> smt5_comp_history_lows = array.new_float()

if isHistoryCollectionActive_SMT5
    if is_new_htf_bar_SMT5
        smt5_session_high := high, smt5_session_low := low
        smt5_session_high_time := time, smt5_session_low_time := time
    else
        if high >= smt5_session_high
            smt5_session_high := high, smt5_session_high_time := time
        if low <= smt5_session_low
            smt5_session_low := low, smt5_session_low_time := time
    if is_new_htf_bar_SMT5
        array.push(smt5_history_highs, smt5_session_high[1]), array.push(smt5_history_times_high, smt5_session_high_time[1])
        array.push(smt5_history_lows, smt5_session_low[1]), array.push(smt5_history_times_low, smt5_session_low_time[1])
        float comp_high = request.security(masterComparisonAsset, timeframeInput_SMT5, high[1], lookahead=barmerge.lookahead_on)
        float comp_low = request.security(masterComparisonAsset, timeframeInput_SMT5, low[1], lookahead=barmerge.lookahead_on)
        array.push(smt5_comp_history_highs, comp_high), array.push(smt5_comp_history_lows, comp_low)

// IMMEDIATE PIVOT PLOTTING - MOVED OUTSIDE HTF BAR CONDITION
if showPivotCrosses_SMT5 and array.size(smt5_history_highs) > 0
    int pivot_check_index = array.size(smt5_history_highs) - 1 - rightBars_SMT5
    if pivot_check_index >= 0
        if checkForPivot(smt5_history_highs, pivot_check_index, leftBars_SMT5, rightBars_SMT5, true)
            drawPivotCross(smt5_PivotLabels, array.get(smt5_history_times_high, pivot_check_index), array.get(smt5_history_highs, pivot_check_index), phColor_SMT5)
        if checkForPivot(smt5_history_lows, pivot_check_index, leftBars_SMT5, rightBars_SMT5, false)
            drawPivotCross(smt5_PivotLabels, array.get(smt5_history_times_low, pivot_check_index), array.get(smt5_history_lows, pivot_check_index), plColor_SMT5)

// =============================================================================
// SMT 5: LOGIC
// =============================================================================
var label pivotA_HighLabel_SMT5 = na, var label visualPivotA_HighLabel_SMT5 = na, var label pivotA_LowLabel_SMT5 = na, var label visualPivotA_LowLabel_SMT5 = na, var line intraDayHighWatchline_SMT5 = na, var line intraDayLowWatchline_SMT5 = na, var label intraDayHighLabel_SMT5 = na, var label intraDayLowLabel_SMT5 = na, var float intraDayWatchlineHighPrice_SMT5 = na, var float intraDayWatchlineLowPrice_SMT5 = na, var bool ltfMainAssetInvalidatedHigh_SMT5 = false, var bool ltfCompAssetInvalidatedHigh_SMT5 = false, var bool ltfMainAssetInvalidatedLow_SMT5 = false, var bool ltfCompAssetInvalidatedLow_SMT5 = false
var array<line> smtConfirmedLines_SMT5 = array.new_line(), var array<label> smtConfirmedLabels_SMT5 = array.new_label()

cleanupSmtDrawings5() =>
    for l in smtConfirmedLines_SMT5
        line.delete(l)
    array.clear(smtConfirmedLines_SMT5)
    for l in smtConfirmedLabels_SMT5
        label.delete(l)
    array.clear(smtConfirmedLabels_SMT5)
    label.delete(pivotA_HighLabel_SMT5), label.delete(visualPivotA_HighLabel_SMT5)
    label.delete(pivotA_LowLabel_SMT5), label.delete(visualPivotA_LowLabel_SMT5)
    line.delete(intraDayHighWatchline_SMT5), label.delete(intraDayHighLabel_SMT5)
    line.delete(intraDayLowWatchline_SMT5), label.delete(intraDayLowLabel_SMT5)

if isSmtLogicActive_SMT5
    bool isWithinTimeSession = isWithinAnySession()
    string shortAssetName = getTicker(masterComparisonAsset)
    float atr_SMT5 = ta.atr(14)
    float y_offset_SMT5 = atr_SMT5 * 0.1
    if is_new_htf_bar_SMT5
        int pivot_idx = array.size(smt5_history_highs) - 1 - rightBars_SMT5
        if pivot_idx >= 0
            bool is_main_pivot_high = checkForPivot(smt5_history_highs, pivot_idx, leftBars_SMT5, rightBars_SMT5, true)
            bool is_comp_pivot_high = checkForPivot(smt5_comp_history_highs, pivot_idx, leftBars_SMT5, rightBars_SMT5, true)
            if is_main_pivot_high and is_comp_pivot_high
                float mainHtfPivotHigh = array.get(smt5_history_highs, pivot_idx)
                float compHtfPivotHigh = array.get(smt5_comp_history_highs, pivot_idx)
                int smt_main_pivot_time = array.get(smt5_history_times_high, pivot_idx)
                if not na(pivotA_HighLabel_SMT5)
                    if (mainHtfPivotHigh - label.get_y(pivotA_HighLabel_SMT5)) * (compHtfPivotHigh - str.tonumber(label.get_text(pivotA_HighLabel_SMT5))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt5_history_times_high, i) > label.get_x(pivotA_HighLabel_SMT5)
                                if array.get(smt5_history_highs, i) > label.get_y(pivotA_HighLabel_SMT5)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT5), str.tostring(leftBars_SMT5), str.tostring(rightBars_SMT5))
                            line newLine = line.new(label.get_x(pivotA_HighLabel_SMT5), label.get_y(pivotA_HighLabel_SMT5), smt_main_pivot_time, mainHtfPivotHigh, xloc = xloc.bar_time, color=color.new(phColor_SMT5, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT5, "SMT Bearish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT5, 75), textcolor=color.white, style=label.style_label_down, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT5, newLine), array.push(smtConfirmedLabels_SMT5, newLabel)
                            if enableAlerts_SMT5
                                alert("Confirmed Bearish SMT on SMT TF5", alert.freq_once_per_bar)
                line.delete(intraDayHighWatchline_SMT5), intraDayHighWatchline_SMT5 := na, label.delete(intraDayHighLabel_SMT5), intraDayHighLabel_SMT5 := na, intraDayWatchlineHighPrice_SMT5 := na
                label.delete(pivotA_HighLabel_SMT5), label.delete(visualPivotA_HighLabel_SMT5)
                pivotA_HighLabel_SMT5 := label.new(smt_main_pivot_time, mainHtfPivotHigh, str.tostring(compHtfPivotHigh), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_HighLabel_SMT5 := label.new(smt_main_pivot_time, mainHtfPivotHigh + y_offset_SMT5, "A", xloc=xloc.bar_time, style=label.style_label_down, color=color.new(phColor_SMT5, 25), textcolor=color.white, size=size.small, tooltip="Pivot A High")
                ltfMainAssetInvalidatedHigh_SMT5 := false, ltfCompAssetInvalidatedHigh_SMT5 := false
            bool is_main_pivot_low = checkForPivot(smt5_history_lows, pivot_idx, leftBars_SMT5, rightBars_SMT5, false)
            bool is_comp_pivot_low = checkForPivot(smt5_comp_history_lows, pivot_idx, leftBars_SMT5, rightBars_SMT5, false)
            if is_main_pivot_low and is_comp_pivot_low
                float mainHtfPivotLow = array.get(smt5_history_lows, pivot_idx)
                float compHtfPivotLow = array.get(smt5_comp_history_lows, pivot_idx)
                int smt_main_pivot_time = array.get(smt5_history_times_low, pivot_idx)
                if not na(pivotA_LowLabel_SMT5)
                    if (mainHtfPivotLow - label.get_y(pivotA_LowLabel_SMT5)) * (compHtfPivotLow - str.tonumber(label.get_text(pivotA_LowLabel_SMT5))) < 0
                        bool wasPivotARun = false
                        for i = pivot_idx - 1 to 0
                            if array.get(smt5_history_times_low, i) > label.get_x(pivotA_LowLabel_SMT5)
                                if array.get(smt5_history_lows, i) < label.get_y(pivotA_LowLabel_SMT5)
                                    wasPivotARun := true, break
                            else
                                break
                        if not wasPivotARun and isWithinTimeSession
                            string confirmedTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}"
                            string baseInfoText = str.format(confirmedTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT5), str.tostring(leftBars_SMT5), str.tostring(rightBars_SMT5))
                            line newLine = line.new(label.get_x(pivotA_LowLabel_SMT5), label.get_y(pivotA_LowLabel_SMT5), smt_main_pivot_time, mainHtfPivotLow, xloc = xloc.bar_time, color=color.new(plColor_SMT5, 40), width=2)
                            label newLabel = label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT5, "SMT Bullish\n" + baseInfoText + "\nStatus: Confirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT5, 75), textcolor=color.white, style=label.style_label_up, size=size.normal, textalign=text.align_left)
                            array.push(smtConfirmedLines_SMT5, newLine), array.push(smtConfirmedLabels_SMT5, newLabel)
                            if enableAlerts_SMT5
                                alert("Confirmed Bullish SMT on SMT TF5", alert.freq_once_per_bar)
                line.delete(intraDayLowWatchline_SMT5), intraDayLowWatchline_SMT5 := na, label.delete(intraDayLowLabel_SMT5), intraDayLowLabel_SMT5 := na, intraDayWatchlineLowPrice_SMT5 := na
                label.delete(pivotA_LowLabel_SMT5), label.delete(visualPivotA_LowLabel_SMT5)
                pivotA_LowLabel_SMT5 := label.new(smt_main_pivot_time, mainHtfPivotLow, str.tostring(compHtfPivotLow), xloc = xloc.bar_time, style=label.style_none, textcolor=color.new(color.white, 100))
                visualPivotA_LowLabel_SMT5 := label.new(smt_main_pivot_time, mainHtfPivotLow - y_offset_SMT5, "A", xloc=xloc.bar_time, style=label.style_label_up, color=color.new(plColor_SMT5, 25), textcolor=color.white, size=size.small, tooltip="Pivot A Low")
                ltfMainAssetInvalidatedLow_SMT5 := false, ltfCompAssetInvalidatedLow_SMT5 := false
    if enableEarlySmtDetection_SMT5 and intradayTimeframe_SMT5 != '' and timeframe.in_seconds(timeframe.period) <= timeframe.in_seconds(intradayTimeframe_SMT5)
        bool is_new_intraday_bar = ta.change(time(intradayTimeframe_SMT5)) != 0
        var float intraday_session_high_SMT5 = high, var float intraday_session_low_SMT5 = low, var int intraday_session_high_time_SMT5 = time, var int intraday_session_low_time_SMT5 = time
        var string usedLtfTimeframe_SMT5 = intradayTimeframe_SMT5
        float intra_comp_high_realtime_SMT5 = request.security(masterComparisonAsset, intradayTimeframe_SMT5, high, lookahead=barmerge.lookahead_off)
        usedLtfTimeframe_SMT5 := intradayTimeframe_SMT5
        if na(intra_comp_high_realtime_SMT5)
            intra_comp_high_realtime_SMT5 := request.security(masterComparisonAsset, '15', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT5 := '15'
        if na(intra_comp_high_realtime_SMT5)
            intra_comp_high_realtime_SMT5 := request.security(masterComparisonAsset, '60', high, lookahead=barmerge.lookahead_off), usedLtfTimeframe_SMT5 := '60'
        float intra_comp_low_realtime_SMT5 = request.security(masterComparisonAsset, intradayTimeframe_SMT5, low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT5)
            intra_comp_low_realtime_SMT5 := request.security(masterComparisonAsset, '15', low, lookahead=barmerge.lookahead_off)
        if na(intra_comp_low_realtime_SMT5)
            intra_comp_low_realtime_SMT5 := request.security(masterComparisonAsset, '60', low, lookahead=barmerge.lookahead_off)
        var float intraday_comp_session_high_SMT5 = intra_comp_high_realtime_SMT5, var float intraday_comp_session_low_SMT5 = intra_comp_low_realtime_SMT5
        if is_new_intraday_bar
            intraday_session_high_SMT5 := high, intraday_session_low_SMT5 := low, intraday_session_high_time_SMT5 := time, intraday_session_low_time_SMT5 := time
            intraday_comp_session_high_SMT5 := intra_comp_high_realtime_SMT5, intraday_comp_session_low_SMT5 := intra_comp_low_realtime_SMT5
        else
            if high > intraday_session_high_SMT5
                intraday_session_high_SMT5 := high, intraday_session_high_time_SMT5 := time
            if low < intraday_session_low_SMT5
                intraday_session_low_SMT5 := low, intraday_session_low_time_SMT5 := time
            if intra_comp_high_realtime_SMT5 > intraday_comp_session_high_SMT5
                intraday_comp_session_high_SMT5 := intra_comp_high_realtime_SMT5
            if intra_comp_low_realtime_SMT5 < intraday_comp_session_low_SMT5
                intraday_comp_session_low_SMT5 := intra_comp_low_realtime_SMT5
        if is_new_intraday_bar
            float ltf_main_high = intraday_session_high_SMT5[1], float ltf_main_low = intraday_session_low_SMT5[1]
            float intra_comp_high = intraday_comp_session_high_SMT5[1], float intra_comp_low = intraday_comp_session_low_SMT5[1]
            if not na(pivotA_HighLabel_SMT5)
                if not ltfMainAssetInvalidatedHigh_SMT5 and ltf_main_high > label.get_y(pivotA_HighLabel_SMT5)
                    ltfMainAssetInvalidatedHigh_SMT5 := true
                if not ltfCompAssetInvalidatedHigh_SMT5 and intra_comp_high > str.tonumber(label.get_text(pivotA_HighLabel_SMT5))
                    ltfCompAssetInvalidatedHigh_SMT5 := true
                if ltfMainAssetInvalidatedHigh_SMT5 and ltfCompAssetInvalidatedHigh_SMT5
                    label.delete(pivotA_HighLabel_SMT5), pivotA_HighLabel_SMT5 := na, label.delete(visualPivotA_HighLabel_SMT5), visualPivotA_HighLabel_SMT5 := na
                    line.delete(intraDayHighWatchline_SMT5), intraDayHighWatchline_SMT5 := na, label.delete(intraDayHighLabel_SMT5), intraDayHighLabel_SMT5 := na
            if not na(pivotA_LowLabel_SMT5)
                if not ltfMainAssetInvalidatedLow_SMT5 and ltf_main_low < label.get_y(pivotA_LowLabel_SMT5)
                    ltfMainAssetInvalidatedLow_SMT5 := true
                if not ltfCompAssetInvalidatedLow_SMT5 and intra_comp_low < str.tonumber(label.get_text(pivotA_LowLabel_SMT5))
                    ltfCompAssetInvalidatedLow_SMT5 := true
                if ltfMainAssetInvalidatedLow_SMT5 and ltfCompAssetInvalidatedLow_SMT5
                    label.delete(pivotA_LowLabel_SMT5), pivotA_LowLabel_SMT5 := na, label.delete(visualPivotA_LowLabel_SMT5), visualPivotA_LowLabel_SMT5 := na
                    line.delete(intraDayLowWatchline_SMT5), intraDayLowWatchline_SMT5 := na, label.delete(intraDayLowLabel_SMT5), intraDayLowLabel_SMT5 := na
            int ltf_main_high_time = intraday_session_high_time_SMT5[1], int ltf_main_low_time = intraday_session_low_time_SMT5[1]
            if not na(pivotA_HighLabel_SMT5)
                bool alreadyInvalidated = ltfMainAssetInvalidatedHigh_SMT5 and ltfCompAssetInvalidatedHigh_SMT5
                if not alreadyInvalidated and (ltf_main_high - label.get_y(pivotA_HighLabel_SMT5)) * (intra_comp_high - str.tonumber(label.get_text(pivotA_HighLabel_SMT5))) < 0 and (na(intraDayWatchlineHighPrice_SMT5) or ltf_main_high > intraDayWatchlineHighPrice_SMT5) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT5), str.tostring(leftBars_SMT5), str.tostring(rightBars_SMT5), formatTimeframe(usedLtfTimeframe_SMT5))
                    line.delete(intraDayHighWatchline_SMT5), label.delete(intraDayHighLabel_SMT5)
                    intraDayHighWatchline_SMT5 := line.new(label.get_x(pivotA_HighLabel_SMT5), label.get_y(pivotA_HighLabel_SMT5), ltf_main_high_time, ltf_main_high, xloc = xloc.bar_time, style=line.style_dashed, color=phColor_SMT5, width=1)
                    intraDayHighLabel_SMT5 := label.new(ltf_main_high_time, ltf_main_high + y_offset_SMT5, "SMT Bearish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(phColor_SMT5, 75), textcolor=color.white, style=label.style_label_down, textalign=text.align_left)
                    intraDayWatchlineHighPrice_SMT5 := ltf_main_high, ltfMainAssetInvalidatedHigh_SMT5 := false, ltfCompAssetInvalidatedHigh_SMT5 := false
                    if enableAlerts_SMT5
                        alert("Potential Bearish SMT on SMT TF 5", alert.freq_once_per_bar)
            if not na(pivotA_LowLabel_SMT5)
                bool alreadyInvalidated = ltfMainAssetInvalidatedLow_SMT5 and ltfCompAssetInvalidatedLow_SMT5
                if not alreadyInvalidated and (ltf_main_low - label.get_y(pivotA_LowLabel_SMT5)) * (intra_comp_low - str.tonumber(label.get_text(pivotA_LowLabel_SMT5))) < 0 and (na(intraDayWatchlineLowPrice_SMT5) or ltf_main_low < intraDayWatchlineLowPrice_SMT5) and isWithinTimeSession
                    string ltfBaseTextTemplate = "Vs: {0}\nTimeframe: {1}\nStrength: {2}-{3}\nLTF Detection: {4}"
                    string ltfBaseInfoText = str.format(ltfBaseTextTemplate, shortAssetName, formatTimeframe(timeframeInput_SMT5), str.tostring(leftBars_SMT5), str.tostring(rightBars_SMT5), formatTimeframe(usedLtfTimeframe_SMT5))
                    line.delete(intraDayLowWatchline_SMT5), label.delete(intraDayLowLabel_SMT5)
                    intraDayLowWatchline_SMT5 := line.new(label.get_x(pivotA_LowLabel_SMT5), label.get_y(pivotA_LowLabel_SMT5), ltf_main_low_time, ltf_main_low, xloc = xloc.bar_time, style=line.style_dashed, color=plColor_SMT5, width=1)
                    intraDayLowLabel_SMT5 := label.new(ltf_main_low_time, ltf_main_low - y_offset_SMT5, "SMT Bullish\n" + ltfBaseInfoText + "\nStatus: Unconfirmed", xloc = xloc.bar_time, color=color.new(plColor_SMT5, 75), textcolor=color.white, style=label.style_label_up, textalign=text.align_left)
                    intraDayWatchlineLowPrice_SMT5 := ltf_main_low, ltfMainAssetInvalidatedLow_SMT5 := false, ltfCompAssetInvalidatedLow_SMT5 := false
                    if enableAlerts_SMT5
                        alert("Potential Bullish SMT on SMT TF 5", alert.freq_once_per_bar)
    if not na(visualPivotA_HighLabel_SMT5)
        label.set_color(visualPivotA_HighLabel_SMT5, showPivotALabel ? color.new(phColor_SMT5, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_HighLabel_SMT5, showPivotALabel ? color.white : color.new(color.white, 100))
    if not na(visualPivotA_LowLabel_SMT5)
        label.set_color(visualPivotA_LowLabel_SMT5, showPivotALabel ? color.new(plColor_SMT5, 25) : color.new(color.white, 100))
        label.set_textcolor(visualPivotA_LowLabel_SMT5, showPivotALabel ? color.white : color.new(color.white, 100))
else
    cleanupSmtDrawings5()
    pivotA_HighLabel_SMT5 := na, visualPivotA_HighLabel_SMT5 := na, pivotA_LowLabel_SMT5 := na, visualPivotA_LowLabel_SMT5 := na
    intraDayHighWatchline_SMT5 := na, intraDayHighLabel_SMT5 := na, intraDayLowWatchline_SMT5 := na, intraDayLowLabel_SMT5 := na